### ISSUE TITLE
Not working :/

### ISSUE THREAD

**Issue by reintroducing** [sapegin/react-styleguidist#10]
This looks like a fantastic little module but I can't seem to get it working.  I'm using Browserify normally as my bundler (not webpack for local dev) with ES6 React components.  Here is my config:

```
module.exports = {
    title: 'SpotHero React Components',
    rootDir: './',
    components: 'frontend/src/js/components/**/*.jsx',
    styleguideDir: './spothero/static/main/uniform/docs-react'
};
```

If I run the build script and nothing else, the resulting HTML page shows this error:

```
Error: HtmlWebpackPlugin: Unable to read HTML template "./src/templates/index.html"
```

If I try to run the server for local dev I just get:

```
Cannot GET /
```

When I look at my Terminal window I see this:

```
[185] ./~/react-styleguidist/~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/react-styleguidist/~/postcss-loader!./~/react-styleguidist/~/sanitize.css/dist/sanitize.css 2.17 kB {0} [built]
  [186] ./~/react-styleguidist/~/style-loader/addStyles.js 6.09 kB {0} [built]
  [187] ./~/react-styleguidist/src/styles.css 1.25 kB {0} [built]

ERROR in ./frontend/src/js/components/breadcrumbs/Breadcrumbs.jsx
Module parse failed: /Users/mprzybylski/Work/SpotHero/SpotHero-Django/frontend/src/js/components/breadcrumbs/Breadcrumbs.jsx Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React, {Component, PropTypes} from 'react';
|
| class Breadcrumbs extends Component {
 @ ./~/react-styleguidist/loaders/styleguide.loader.js! 3:139-253
```

Over and over for all my components that its trying to parse.

Any ideas what I'm doing wrong?  Really appreciate any help you could offer.

**Comment by sapegin** [comment]
Sure, I forget to add .jsx extension.

**Comment by reintroducing** [comment]
I'm not familiar with Webpack but is this something I should do myself extending the config or needs to be added to the project by you?

**Comment by sapegin** [comment]
You can do something like [this](https://github.com/sapegin/react-styleguidist/issues/9#issuecomment-145065708) but I’ll add .jsx support soon.
