### ISSUE TITLE
Missing stringify in the loader?

### ISSUE THREAD

**Issue by qur2** [sapegin/react-styleguidist#100]
Hi,

I was trying to build a styleguide for my project and it was failing with a JSON.parse error:
```
ERROR in ./src/components/ui/Button.js
Module build failed: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.module.exports (/the-project/node_modules/json-loader/index.js:7:48)
 @ ./~/react-styleguidist/loaders/styleguide.loader.js! 3:154-221

ERROR in ./src/components/ui/Link.js
Module build failed: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.module.exports (/the-project/node_modules/json-loader/index.js:7:48)
 @ ./~/react-styleguidist/loaders/styleguide.loader.js! 3:455-520

ERROR in ./src/components/ui/SvgIcon.js
Module build failed: SyntaxError: Unexpected token i
    at Object.parse (native)
    at Object.module.exports (/the-project/node_modules/json-loader/index.js:7:48)
 @ ./~/react-styleguidist/loaders/styleguide.loader.js! 3:761-829
```

I fixed it by modifying the `processComponent` of the styleguide loader like so:
```javascript
'module: ' + JSON.stringify(requireIt(filepath)),
```

Any thought on that? I obviously would like to avoid forking for that, since I assume it's an isolated problem.

Those are my webpack packages:
```
⟩ npm list | grep webpack                                                                                                                                         js:v5.2.0
├─┬ extract-text-webpack-plugin@0.9.1
├─┬ webpack@1.12.14
│ └─┬ webpack-core@0.6.8
├─┬ webpack-dev-server@1.14.1
│ └─┬ webpack-dev-middleware@1.5.1
```

Thanks for your help,
Aurélien.

**Comment by qur2** [comment]
I just the same for the example readme file loading:

```
ERROR in ./~/react-styleguidist/loaders/examples.loader.js!./src/components/ui/Readme.md
Module build failed: SyntaxError: Unexpected token R
    at Object.parse (native)
    at Object.module.exports (/the-project/node_modules/json-loader/index.js:7:48)
 @ ./~/react-styleguidist/loaders/styleguide.loader.js! 3:319-395 3:692-768 3:1080-1156
```

In the same way, if I wrap the `requireIt` call in the `processComponent` function, I get passed this error. However, in this case, it later fails when the components are rendered with:

```
// here examples is a string: 'require("examples!/the-project/src/components/ui/Readme.md")'
Uncaught TypeError: examples.map is not a function
```

**Comment by sapegin** [comment]
> Any thought on that? 

Instead of fixing it’ll break style guide even more ;-) I also don’t understand why do you load JavaScript with JSON loader.

What version of react-styleguidist do you use? Can you show your style guide config?

**Comment by qur2** [comment]
Oh!! Thank you, I actually misconfigured the JSON loader, I completely omitted the test key for that loader (mistakenly, not on purpose at all):
```javascript
{
      loaders: ['json'],
      include: /\.json$/,
}
```

It works fine for dev & build, but only started to fail with styleguidist. I changed the loader config to:
```javascript
{
      loaders: ['json'],
      test: /\.json$/,
      include: /\.json$/,
}
```

And it works as expected. Thank you for your hint, it did put me on the correct track.

**Comment by mik01aj** [comment]
@qur2 thanks for reporting what your problem actually was. It can be helpful for others.

**Comment by sapegin** [comment]
@mik01aj Maybe we can show more warnings?

I think we can also use [webpack-validator](https://github.com/kentcdodds/webpack-validator) but right now it’s very basic.

**Comment by mik01aj** [comment]
@sapegin No, I don't think so. We can think about it if more people have this problem.-
