### ISSUE TITLE
ERROR in ./~/react-codemirror/src/codemirror.js Module parse failed

### ISSUE THREAD

**Issue by shubhamsizzles** [sapegin/react-styleguidist#103]
I'm following the guide, but I can't get past this error. My config file looks like:
```javascript
var path = require('path');

module.exports = {
  title: 'My Great Style Guide',
  components: 'src/**/*.jsx',
  updateWebpackConfig: function (webpackConfig, env) {
    var dir = path.join(__dirname, 'src');
    webpackConfig.module.loaders.push(
      {
        test: /\.scss$/,
        include: dir,
        exclude: /node_modules/,
        loaders: [
          "style-loader",
          "css-loader?sourceMap",
          "postcss-loader",
          "sass-loader?sourceMap",
        ],
      },
      {
        test: /\.css$/,
        include: dir,
        exclude: /node_modules/,
        loaders: [
          "style-loader",
          "css-loader?sourceMap",
          "postcss-loader",
        ],
      },
      {
        test: /\.json$/,
        include: dir,
        exclude: /node_modules/,
        loader: "json-loader",
      },
      {
        test: /\.(png|jpg|svg)$/,
        include: dir,
        exclude: /node_modules/,
        loader: "url-loader?limit=10000",
      },
      {
        test: /\.jsx?$/,
        include: dir,
        exclude: /node_modules/,
        loader: "babel",
        query: {
          cacheDirectory: true,
          // plugins: ["transform-runtime"],
          presets: ["es2015", "react", "stage-0"],
        },
      }
    );

    webpackConfig.resolve = {
      extensions: ["", ".js", ".jsx", ".scss", ".json", ".png", ".svg", ".jpg"],
      modulesDirectories: [
        "src",
        "node_modules",
      ],
    };
    return webpackConfig;
  },
};
```

This is the error summary : 

```
ERROR in ./~/react-codemirror/src/codemirror.js
Module parse failed: /Users/xyz/node_modules/react-codemirror/src/codemirror.js Line 77: Unexpected token <
You may need an appropriate loader to handle this file type.
| 		);
| 		return (
| 			<div className={editorClassName}>
| 				<textarea ref="textarea" name={this.props.path} defaultValue={this.props.value} autoComplete="off" />
| 			</div>
 @ ./~/react-codemirror/lib/Codemirror.js 6:6-27
```

**Comment by sapegin** [comment]
I think that’s because you have `src` in `modulesDirectories`. So any `require('codemirror')` will try to load `src/codemirror.js` first. Try to use absolute path.

**Comment by shubhamsizzles** [comment]
@sapegin My project already relies on `moduleDirectories` for importing subcomponents within components. I'm afraid its not something I can change. Surely, there must be some way around this?

**Comment by shubhamsizzles** [comment]
I fixed that error by added `node_modules` to `wepackConfig.exclude`. Webpack now runs successfully, but now the client has problems with hot reloading. 

`module.exports = require("webpack-hot-middleware/client");
require not defined`

**Comment by sapegin** [comment]
> My project already relies on moduleDirectories

You really shouldn’t rely on hacks like this ;-)

**Comment by shubhamsizzles** [comment]
@sapegin It isn't a hack. Writing 
`import "components/componentA.jsx/"` 
is neater than
`import ../../../../components/componentA.jsx"`,
 if I add "src" to moduleDirectories.

**Comment by sapegin** [comment]
It is a hack because you’re just creating problems for yourself and anyone who will support your code later. In your case you should use `alias`. Anyway this issue isn’t related to React Styleguidist.

**Comment by oliverturner** [comment]
@shubhamsizzles my experience is that - as much it feels elegant to be able to reference your deps like this - it just leads to issues and confusion down the line. Not sure I'd go so far as to call it a hack (since webpack allows you to do this)... maybe an anti-pattern? I'd recommend being as explicit as possible.

**Comment by mik01aj** [comment]
[StackOverflow folks recommend `alias`.](http://stackoverflow.com/questions/30084723/webpack-resolve-moduledirectories). :)
