### ISSUE TITLE
Syntax highlighting not working in codemirror

### ISSUE THREAD

**Issue by shubhamsizzles** [sapegin/react-styleguidist#105]
What could I be doing wrong?

<img width="974" alt="screen shot 2016-03-15 at 8 03 52 pm" src="https://cloud.githubusercontent.com/assets/8946207/13781365/18b250ce-eae9-11e5-9169-394779e80cfa.png">

My markdown looks like:

```md
React component example:

    <div>
      <JumpingDots/>
    </div>
```

Config:

```
module.exports = {
 title: 'My Great Style Guide',
  components: 'src/**/*.jsx',
  highlightTheme: "material",
//shortened for brevity
}
```

**Comment by sapegin** [comment]
Does it work with the default theme?

**Comment by shubhamsizzles** [comment]
@sapegin it doesn't.

**Comment by sapegin** [comment]
Strange, it works fine for everybody else.

**Comment by mik01aj** [comment]
@sapegin I also noticed that highlighting doesn't work when you build (rather then use server).

**Comment by sapegin** [comment]
@mik01aj But it works [on the example page](http://react-styleguidist.js.org/).

**Comment by shubhamsizzles** [comment]
Hmm... Isn't the highlighting applied by codemirror library itself? What could be possibly going wrong? Don't see any console errors.

**Comment by sapegin** [comment]
It is. Does it generate classes for highlighting?

![](http://wow.sapegin.me/1A3G2l1O3r0e/Image%202016-03-15%20at%204.07.51%20PM.png)

**Comment by mik01aj** [comment]
@sapegin mist. I checked it in my build and it turned out it's about props rather then code in CodeMirror, and they don't have the colour because of some strange CSS issue - this is the computed style:

![image](https://cloud.githubusercontent.com/assets/3027415/13782919/71803a9c-eac9-11e5-80a7-467bbe67393d.png)

I have no idea why it ends up being black. But this on seems to be some other issue than what @shubhamsizzles  reported.

**Comment by sapegin** [comment]
It maybe because Webpack applies CSS snippets in unpredictable order. Have no other explanation now.

**Comment by mik01aj** [comment]
@sapegin I figured out in my case it's overridden by `.ReactStyleguidist-common__reset {all: initial;}`.

**Comment by sapegin** [comment]
@mik01aj Could you fix that? Because I can’t reproduce it.

**Comment by mik01aj** [comment]
I'd just remove [this line](https://github.com/sapegin/react-styleguidist/blob/0ff2b2f93dffe30046d8c20c819bf9aeb28b209e/src/styles/common.css#L28)...

**Comment by shubhamsizzles** [comment]
@sapegin  In my case, the only classes I see are ` CodeMirror-line ` and ` CodeMirror-code ` . No other classes, although identifiers have their own span/div tags.

**Comment by sapegin** [comment]
I’ve updated CodeMirror and now we’re using its own JSX mode. Feel free to reopen if you still experience this issue.

**Comment by sapegin** [comment]
Just had the same issue after upgrading Styleguidist in my project. Fixed by removing `node_modules` folder and reinstalling dependencies ;-)

**Comment by sapegin** [comment]
Finally I was able to really investigate and fix this issue: https://github.com/styleguidist/react-styleguidist/issues/611
