### ISSUE TITLE
Reuse react-styleguidist as a React component, not a separate app?

### ISSUE THREAD

**Issue by sompylasar** [sapegin/react-styleguidist#107]
Like this:
https://github.com/skidding/react-component-playground

Is this possible?

I'd like to plug it into my app on a separate route.

**Comment by sapegin** [comment]
I’m not sure it’s possible because we have a lot of stuff in Webpack loaders. It might work with a lot of copy-pasting from Styleguidist to your app so you can use components from Styleguidist but I’m not sure it’s worth it.

**Comment by sapegin** [comment]
Maybe better solution is just to publish it as a static page and have a link in your app. And use Styleguidist server to develop new components.

**Comment by mik01aj** [comment]
@sompylasar I think you could actually try this way: try to modify the webpack config (that one for static website, produced from `makeWebpackConfig`) to build a bundle with just the root component exposed.

**Comment by sompylasar** [comment]
OK, then, I think, I will have to run `styleguidist server` as a child process and expose it on a routed page in an iframe.

For future, it would be very useful to expose a JS API to take a config object and start the server, not just the CLI with the file-based config.

**Comment by sapegin** [comment]
Yeah, and I’ll be happy to merge such pull request ;-)
