### ISSUE TITLE
Ability to ignore components

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#11]
Array of regexp masks or function.

**Comment by mik01aj** [comment]
Or maybe a glob pattern? See: https://github.com/isaacs/node-glob#options

Then, instead of:
```
componentSources = glob.sync(path.join(config.rootDir, config.components));
```
you could do:
```
componentSources = glob.sync(config.components, {
    cwd: config.rootDir,
    ignore: config.ignorePatterns,
});
```

**Comment by sapegin** [comment]
Nice, didn’t know about that!

**Comment by mik01aj** [comment]
And maybe even this feature is not necessary at all as you can use a function directly in the config. We'd just need to add an example to the README.

**Comment by sapegin** [comment]
That’s even better. Can you make a PR for that?

**Comment by sapegin** [comment]
(Actually you can commit directly to the repo now ;–)

**Comment by panayi** [comment]
An additional configurable option that may be useful, is to be able to include components only when a sibling `.md` file is present.

```javascript
  getExampleFilename: function(componentpath) {
    return componentpath.replace(/\.jsx?$/, '.md');
  },
  components: function(config, glob) {
    const regex = /\/[A-Z][A-Za-z]*\.jsx$/
    return glob.sync(config.rootDir + '/**/*.jsx').filter(function(module) {
      const mdFile = config.getExampleFilename(module);
      try {
          const mdFileWithSameNameExists = fs.statSync(mdFile);
          return mdFileWithSameNameExists && mdFileWithSameNameExists.isFile();
        } catch(err) {
          return !(err && err.code === 'ENOENT');
        }
    });
  }
```

**Comment by sapegin** [comment]
@panayi Yeah, pull request for that would be very helpful.

**Comment by panayi** [comment]
I'm thinking of two options:

1. A config option `includeOnlyComponentsWithExampleFile:true|false`.
2. A webpack-loader type of syntax: `hasExample` that can be passed in `components`

```javascript
module.exports = {
  components: 'hasExample!/**/*.jsx'
}
```
In case `components` is a function we can also provide a helper `hasExample` function:

```javascript
module.exports = {
  components: function(config, glob) {
    const regex = /\/[A-Z][A-Za-z]*\.jsx$/
    return glob.sync(config.rootDir + '/**/*.jsx').filter(function(module) {
      return config.hasExample(module);
      // alternatively, in order to avoid overriding `hasExample`,
      // the package exports the function and...
      // import { hasExample } from 'react-styleguidist'
      // return hasExample(module)
    });
  }
}
```

**Comment by sapegin** [comment]
Not sure the second options has any benefits but it’s much more complicated.

includeOnlyComponentsWithExampleFile → skipComponentsWithoutReadme?

**Comment by panayi** [comment]
You are right that the 2nd option is unnecessary complex. Implemented 1st option: https://github.com/sapegin/react-styleguidist/pull/38

**Comment by mik01aj** [comment]
imho `skipComponentsWithoutReadme` name is not so relevant, because the `Readme.md` name can be changed in the config to anything else. We have `getExampleFilename` in config, so why not `skipComponentsWithoutExample` (or `...examples` - the pluralization is not consistent anyway)?

**Comment by sapegin** [comment]
@mik01aj good point, I didn’t think about that.

**Comment by mik01aj** [comment]
I guess this ticket can be closed now.

**Comment by sapegin** [comment]
We should document ignoring. I think we can add a section like *Recipes* for such things. So I’ll leave it open for now ;-)

**Comment by operatino** [comment]
In SourceJS, during navigation tree build I only search for component folders with some hook inside, like `info.json`. Maybe in this case it also be wise to include by default only those components, which have `readme.md` next to it?

**Comment by sapegin** [comment]
There’s an option to do that — skipComponentsWithoutExample ;-)

**Comment by mik01aj** [comment]
@sapegin could you create `documentation` label for this kind of tickets? We have several, I'd like to group them.

**Comment by jamieholliday** [comment]
So I have skipComponentsWithoutExample: true in config but just noticed a weird behaviour when having nested components
I have these 3 components:
Grid
Row
Column
In Grid/Readme.md I have this:
```
const Row = require('components/Row');
const Column = require('components/Column');
const Grid = require('components/Grid');
<Grid>
  <Row>
    <Column>
    ....
    </Column>
  </Row>
</Grid>
```
It now doesn't matter if I have Readme.md files in any of the other component folders or not I get the entries for all 3 components in the styleguide and duplicate example code for each. I'd like to have different example for each component by supplying different Readme files or even just ignore the <Row /> and <Column /> components completely from styleguide

**Comment by AoDev** [comment]
Could we add a directive in a comment at the top of a component file like many linters do for example?

```
/*react-styleguide: ignore*/

import React from 'react'

... component code
```

**Comment by mik01aj** [comment]
Why would this be better than ignoring the components in the styleguide config?

**Comment by sapegin** [comment]
It also might be difficult to implement. And I’d like to have a style guide config as isolated from the code as possible.

**Comment by AoDev** [comment]
Because right now the styleguide is also documenting some "internal" subcomponents which shouldn't be a concern for the developers who are going to use the main component.

**Comment by mik01aj** [comment]
@AoDev this doesn't answer my question. I didn't ask you why we need ignoring components, I asked you why do you want to do it in the component file instead of the styleguide config (see the comments above for details on how to do it).

**Comment by AoDev** [comment]
Because it's easier to do for the user. Regarding the styleguide config you'd need to create a function / pattern that is heavily dependent on the file names / pattern / file structure.

Files operations like renaming files / moving code around (that sure does not happen all the time), need to be followed by a change in the styleguide config while there wouldn't be anything to do with this directive.

**Comment by AoDev** [comment]
But, if you have code pattern structure to propose to help it's more than welcomed.
Our structure is similar to AirBnB react styleguide. https://github.com/airbnb/javascript/tree/master/react#naming

**Comment by mik01aj** [comment]
Well, yes, but the same is also true for most build, or test, or lint configs. I still think it's fine as it is.

**Comment by sapegin** [comment]
I’ve added to the FAQ [how to ignore components](https://github.com/sapegin/react-styleguidist/blob/master/docs/FAQ.md#how-to-exclude-some-components-from-style-guide) using the `components` option.

I’m closing this for now. Feel free to submit a pull request if you need a simpler way to ignore components.

**Comment by dfredriksen** [comment]
Link to FAQ is broken
