### ISSUE TITLE
Union elements share same key

### ISSUE THREAD

**Issue by marklundin** [sapegin/react-styleguidist#111]
React is raising the `Encountered two children with the same key, '.$instanceOf'` warning when attempting to render a component with multiple `PropType.instanceOf`s.  It seems that the component keys aren't properly assigned.

Here's a test component that causes the error 

```
import { PropTypes } from 'react'

let EmptyComponent = _ => <div>empty</div>

EmptyComponent.propTypes = {
    someValue:PropTypes.oneOfType([
        PropTypes.instanceOf( Int8Array ),
        PropTypes.instanceOf( Uint8Array )
    ]).isRequired
}

export default EmptyComponent
```
```
warning.js?7f53:45 Warning: flattenChildren(...): Encountered two children with the same key, `.$instanceOf`. Child keys must be unique; when two children share a key, only the first child will be used.
```

I've had a look through the code and think it could be [this](https://github.com/sapegin/react-styleguidist/blob/master/src/rsg-components/Props/Props.js#L120) but can't be sure.

**Comment by marklundin** [comment]
Further info on this. Whilst the above throws the warning, the modified code below does not.

```
import { PropTypes } from 'react'

let EmptyComponent = _ => <div>empty</div>

let oneOfType = [
    PropTypes.instanceOf( Int8Array ),
    PropTypes.instanceOf( Uint8Array )
]

EmptyComponent.propTypes = {
    someValue:PropTypes.oneOfType( oneOfType )
}

export default EmptyComponent
```

**Comment by sapegin** [comment]
Yeah, looks like we shouldn’t use name alone as a key. Could you please submit a pull request with a fix?

**Comment by marklundin** [comment]
opened a PR
