### ISSUE TITLE
Support for Flow types

### ISSUE THREAD

**Issue by MoOx** [sapegin/react-styleguidist#115]
This is more a question. [react-docgen support for flow](https://github.com/reactjs/react-docgen#flow-type-support), but I am not sure that react-styleguidist does.
As a workaround, [there is a babel plugin to transform flow types as props ](https://github.com/brigand/babel-plugin-flow-react-proptypes).

**Comment by MoOx** [comment]
From what I see it should be ok as the result seems following the same format.

**Comment by sapegin** [comment]
It would be nice if you or anyone could check that because I don’t use Flow anywhere.

**Comment by zammer** [comment]
We use flow in our project and everything works fine. :)

**Comment by MoOx** [comment]
I confirm this is working like a charm, without any propTypes (only flow annotation) and no plugin to generate those.
You can safely add a note in the README ;)

**Comment by stereobooster** [comment]
But does it support Flow type definitions like:

```js
type Tab = "TAB1" | "TAB2";
```

It seems not. Still looking into it
