### ISSUE TITLE
Using TypeScript interfaces to describe props — is it ever possible?

### ISSUE THREAD

**Issue by vslinko** [sapegin/react-styleguidist#117]
I'm using React Styleguidist with TypeScript and I don't want to write `propTypes` but I want to have components API described on Styleguidist page.

**Comment by vslinko** [comment]
For future seekers: you can override internal `props` loader and implement your own parser.
https://github.com/sapegin/react-styleguidist/blob/master/loaders/props.loader.js

**Comment by pvasek** [comment]
This is perfect, thanks a lot. I put together a simple implementation of props parser for typescript. 

You can find it here:
https://github.com/pvasek/react-docgen-typescript

**Comment by jarekbb** [comment]
For TypeScript install [styleguidist/react-docgen-typescript](https://github.com/styleguidist/react-docgen-typescript)
