### ISSUE TITLE
Stateless components do not output in build

### ISSUE THREAD

**Issue by marklundin** [sapegin/react-styleguidist#122]
Stateless components such as `export default props => 'text'` are not included in the output when  running `styleguidist build`. I've narrowed it down and found that if the [UglifyJsPlugin](https://github.com/sapegin/react-styleguidist/blob/master/src/make-webpack-config.js#L110) is removed then it works correctly. I guess Uglify may be mangling something with the component somewhere

**Comment by sapegin** [comment]
Stateless components work if you define them [like this](https://github.com/sapegin/react-styleguidist/blob/master/examples/basic/lib/components/Button/Button.js):

```
export default function Button() {}
```
