### ISSUE TITLE
package.json missing in examples folder

### ISSUE THREAD

**Issue by O4epegb** [sapegin/react-styleguidist#125]
Could you please add package.json to each separate example, so you could run them independently from main project? I can't figure out what deps they need. Or if you are too busy to do it yourself, can you tell what deps are needed and i make PR with package.json?
Thank you in advance.

**Comment by sapegin** [comment]
You can install main project dependencies:

```
cd ..
npm install
```

But it’d be nice to make examples independent too. 

~~If you have time please submit a pull request.~~ Just did it in aca5ae472b8d1dfc67dbe7cf08f79e2ccd551431 ;-)
