### ISSUE TITLE
Problems with documenting components from separate library

### ISSUE THREAD

**Issue by O4epegb** [sapegin/react-styleguidist#126]
So, the case:
1. There is a libary on react and typescript
2. I want to make documentation for it
3. But, none of the methods for documenting components does not work for some reason
I'm getting this error every time
```
Error when parsing UisButton.tsx
Error: No suitable component definition found.
```
 (i cant use propTypes method, but i tried all the other ones, including getExampleFilename method)
4. Main thing: i'm just reexporting react-component, like this:
```
import {UisButton} from "uikit";

export default UisButton
```
If i just inline component source code instead of importing and exporting everything suddenly works. What i am doing wrong? Does anybody got that problem before?

(i think my styleguide.config is fine, other setup is good too, because inlining code works, but i cant inline it, because the library is separate package, and i cant place readmes and proptypes inside it, or basically modify in any way)

Also, your library is just insanely good, thank you so much for all your work, good job! I wish I could collaborate, but I'm not experienced enough just yet!

**Comment by sapegin** [comment]
Looks like react-docgen don’t support TypeScript: https://github.com/reactjs/react-docgen/issues/67

**Comment by O4epegb** [comment]
The thing is than everything working if I'm using regular file with code, even in typescript, but not working with reexport. And I checked the same scenario without typescript it didn't worked too.
I checked your examples, there is regular file with component, like Button.jsx and index.js file with reexport too, and you are using component file but if I reconfigure system to work with reexported index.js versions then nothing works.

**Comment by O4epegb** [comment]
You can try to recreate this case, just use index.js files from examples, instead of directly using component files.

**Comment by sapegin** [comment]
I thinks it’s because react-docgen don’t analyze imports and it couldn’t find a component in your file because there’s no component in this file.

**Comment by O4epegb** [comment]
That might be the case. Is it hard to implement this feature? That would be killer feature, with it you could make docs for independent libraries, without touching any internal source code.

**Comment by sapegin** [comment]
Try to ask in [react-docgen repo](https://github.com/reactjs/react-docgen).

**Comment by O4epegb** [comment]
Hm. This is quite strange, I think react-docgene actually analyzes imports, because if you import some other component inside yours - then everything is ok, like in your examples with modal, otherwise it would not work, if I understand correctly. So, if I just make dummy wrapper-component and import my component inside, it should work. I'll test this tomorrow.

**Comment by O4epegb** [comment]
Hey, again!
I tried again today, with version from npm this time, and everything suddenly works!
But i have a question, why props.loader.js in npm version is different from the one in github repo? Someone forgot to commit it? New version of this file fixed all issues, but you need to synchronize them, i think.
Anyway, thanks for the answers, version from npm works well so far, you can close this issue.

**Comment by sapegin** [comment]
The new version is of course in the repo. Actually there are quite a lot of changes since the last release and I’m not sure which causes a regression: https://github.com/sapegin/react-styleguidist/commits/master/loaders/props.loader.js

**Comment by O4epegb** [comment]
This is the version from npm package
http://puu.sh/ogFky/1b319c4749.png

The one in the github repo looks completely different, no? It is also not working, in my case.

**Comment by sapegin** [comment]
>  Actually there are quite a lot of changes since the last release and I’m not sure which causes a regression: https://github.com/sapegin/react-styleguidist/commits/master/loaders/props.loader.js

**Comment by sapegin** [comment]
Feel free to send a pull request with a fix.
