### ISSUE TITLE
Who uses React Styleguidist?

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#127]
Do you use React Styleguidist in your project? Let us know about that! It’d be great if you can share some details: screenshot, link, number of components, etc. 

We use it at [Here](https://company.here.com/here/) for a component library that we use to develop internal tools. Right now we have 41 component and it’s growing:

![](http://wow.sapegin.me/1Y0D2C442y3D/Image%202016-04-14%20at%209.16.07%20AM.png)

**Comment by operatino** [comment]
Interested in [sourcejs-react-styleguidist](https://github.com/sourcejs/sourcejs-react-styleguidist) users? I know @ndelangen uses it quite extensively.

**Comment by sapegin** [comment]
@operatino Yep ;-)

**Comment by ndelangen** [comment]
Me and my team are using [sourcejs-react-styleguidist](sourcejs-react-styleguidist) as @operatino says.
We currently document 58 spec pages, ranging from _Utilities/Colors, Utilities/Fonts, Atoms/Buttons, Atoms/Image, Molecules/Map, Molecules/ProductList, Modules/Hero, Modules/StoreLocator, Scaffolds/Header, Scaffolds/Footer_.

Spec pages are grouped together according to a somewhat [atomic design principle](http://bradfrost.com/blog/post/atomic-web-design/) to the extend that worked for us.

On each spec page there are on average 5 representations of each component, in different states, variations, with different modifiers etc. Some specs only have a single representation, some have over 20.

This is for example how our Atoms/FormElements looks like:

![sourcejs](https://cloud.githubusercontent.com/assets/3070389/14526301/a717dd14-0242-11e6-829f-1ea20971aaf8.png)

**Comment by sapegin** [comment]
@ndelangen Cool, thanks!

**Comment by mik01aj** [comment]
Hello from [LovelyBooks](http://lovelybooks.de)! :)

![screenshot 2016-04-21 13 27 36](https://cloud.githubusercontent.com/assets/3027415/14707398/ea190c46-07c4-11e6-9a24-23193c95790d.png)

Right now we have 50 components.

**Comment by sapegin** [comment]
@mik01aj Awesome!

**Comment by sapegin** [comment]
[Rumble Charts](http://rumbleinc.github.io/rumble-js-charts/), React components for building composable and flexible charts.

![](http://wow.sapegin.me/3W3X1P0B003G/Image%202016-04-25%20at%208.15.54%20AM.png)

/cc @rosko

**Comment by pke** [comment]
I stumbled over this project a couple of weeks ago, starred it and then forgot how it was named and that I had it starred. Last week I was desperately googling anything with *react component documentation by example example.md* but did not find this project. *react components in example.md* finally lead me back to this repo.

Now I can work on our example files for about 80 components/containers and I will present screens later here.
Thanks for creating the project!

**Comment by sapegin** [comment]
@pke Would be interesting to see the result ;-0

**Comment by sapegin** [comment]
[Semantic UI Components for React](https://github.com/hallister/semantic-react).

[![image 2016-05-11 at 3 32 06 pm](https://cloud.githubusercontent.com/assets/70067/15182580/90887508-178d-11e6-9830-a9df957c09fd.png)](http://hallister.github.io/semantic-react/)

/cc @asvetliakov @hallister

**Comment by sapegin** [comment]
Feel free to add your project here!

**Comment by zecaptus** [comment]
Hello from [Whataboon](https://www.whataboon.com) ;)

Change from the original react-styleguidist  (without forking / only webpack aliases) : 
 - Material Design
 - One component / page
 - Collapse Sections

Furture : 
 - 100% Material
 - Subsections  

<img width="1390" alt="capture d ecran 2016-08-03 a 23 03 08" src="https://cloud.githubusercontent.com/assets/7048870/17381893/90e01ce4-59ce-11e6-893b-f8883428ad1d.png">

**Comment by sapegin** [comment]
@zecaptus Wow that’s cool! Thanks for sharing ;-)

**Comment by pke** [comment]
@zecaptus Care to share the webpack config?

**Comment by zecaptus** [comment]
@pke : I'm not really sure, it's really helpfull but here it is.

`styleguide.config.js`
```JS 
var path = require('path');
var glob = require('glob');

module.exports = {
    title: 'Whataboon UI Components Library',
    sections: [
        {name: 'Introduction', content: 'docs/introduction.md'},
        {name: 'UI Components', content: 'docs/ui.md', components: function() {
            return glob.sync(path.resolve(__dirname, 'src/components/**/*.jsx')).filter(function(module) {
                return /\/[A-Z]\w*\.jsx$/.test(module);
            });
        }}
    ],
    showCode: true,
    template: 'config/styleguide/template.html',
    updateWebpackConfig: function(webpackConfig, env) {
        // Your source files folder or array of folders, should not include node_modules
        var dir = path.join(__dirname, 'src');
        var config = path.join(__dirname, 'config/styleguide');

        webpackConfig.resolve.alias['rsg-components/Layout'] = path.join(config, 'Layout');
        webpackConfig.resolve.alias['rsg-components/Wrapper'] = path.join(config, 'Wrapper');

        webpackConfig.module.loaders.push(
            // Babel loader will use your project’s .babelrc
            {
                test: /\.jsx?$/,
                include: [dir, config],
                loader: 'babel'
            },
            // Other loaders that is needed for your components
            {
                test: /\.css$/,
                include: [dir, config],
                loader: 'style!css?modules&importLoaders=1'
            },
            // Image URL config. Generate data URI's for images smaller than 10,000 bytes
            {
                test: /\.(png|gif|jpe?g|svg)$/i,
                include: [dir, config],
                loader: 'url?limit=10000'
            }
        );
        return webpackConfig;
    }
};
```

**Comment by mik01aj** [comment]
Our LovelyBooks styleguide grew much bigger since then. Now we have 72 components with 120 examples. All our examples are also used as unit-tests (we just check that they render without any warnings or errors; this turned out to be a really good test).

![image](https://cloud.githubusercontent.com/assets/3027415/17396959/176a368e-5a36-11e6-8023-aa30c42ca7e3.png)

Good job @sapegin and everyone :)

**Comment by sapegin** [comment]
@mik01aj I like this idea of testing. Could you please share some code?

**Comment by mik01aj** [comment]
@sapegin I did already in https://github.com/sapegin/react-styleguidist/issues/34

**Comment by mik01aj** [comment]
Btw - I found a list here: https://libraries.io/npm/react-styleguidist/dependent-repositories

Interesting examples:

* http://nitive.github.io/react-motion-pack/
* https://nordnet.github.io/nordnet-component-kit/
* https://dialogs.github.io/dialog-web-components/ 👍 
* https://roistat.github.io/react-ui/

**Comment by sapegin** [comment]
@mik01aj we have Dialog in the Showcase in Readme. I can’t add Nordnet because they have removed a link to Styleguidist.

**Comment by kulakowka** [comment]
We finally started using it in production.

![2017-04-25 10 20 06](https://cloud.githubusercontent.com/assets/557190/25373098/eb0dd466-29a0-11e7-8350-b120b91063a1.png)

**Comment by sapegin** [comment]
@kulakowka Awesome!

**Comment by sapegin** [comment]
@kulakowka Could I add your company logo to a site? ;-)

@zecaptus Are you still using Styleguidist? ;-)

@mik01aj Do you know if they are still using Styleguidist?

**Comment by zecaptus** [comment]
@sapegin Yes, I still use it, moreover I will update it to make it work for [`react-native`](https://facebook.github.io/react-native/) with [`exponent`](https://snack.expo.io/), probably in 2018.

**Comment by kulakowka** [comment]
@sapegin We just started developing our components. They will be released in a couple of weeks. Unfortunately, we can not open the source code. No one will be able to see our documentation, except for employees of our company. Does it make sense then to place a logo?

**Comment by sapegin** [comment]
@kulakowka No, it doesn’t ;-)

**Comment by kulakowka** [comment]
I started a new project: [react-bulma](https://github.com/kulakowka/react-bulma) - React.js components for Modern CSS framework based on Flexbox - [https://bulma.io](bulma.io)

![2017-06-01 2 52 24](https://cloud.githubusercontent.com/assets/557190/26658839/5da1e0f8-4675-11e7-8c24-3cf7c9a92275.png)

Docs created with styleguidist: https://kulakowka.github.io/react-bulma/

**Comment by cameron-martin** [comment]
@zecaptus which part of this gives you the one component per page?

**Comment by zecaptus** [comment]
@cameron-martin nothing here.
1/ The trick is to overwrite styleguide components 
2/ parse current component in the url 
3/ and insteadOf showing a list of components, just show it as if it was open in isolated mode.

Hope this can help you ;)

**Comment by ajainvivek** [comment]
I started a new project for [preact-fluid](https://github.com/ajainvivek/preact-fluid) a minimal UI kit for `Preact` 

<img width="696" alt="screen shot 2017-11-24 at 4 37 57 pm" src="https://user-images.githubusercontent.com/1182600/33196933-42a9472c-d136-11e7-858a-a270109dfb2f.png">


Docs created with styleguidist: https://ajainvivek.github.io/preact-fluid/

**Comment by sapegin** [comment]
@ajainvivek Look cool!

**Comment by konradk** [comment]
![React Chat UI Kit](https://static.livechatinc.com/1520/P11Q52CEZH/0219e9f5725826d29a18c64a74487bd1/Screen%20Shot%202017-12-29%20at%2012.49.42.png)

[LiveChat React Chat UI Kit](https://static.livechatinc.com/1520/P11Q52CEZH/0219e9f5725826d29a18c64a74487bd1/Screen%20Shot%202017-12-29%20at%2012.49.42.png)

**Comment by SaraVieira** [comment]
We are also using it at Joyent: https://joyent-ui-toolkit.now.sh/

**Comment by stepancar** [comment]
https://design.alfabank.ru/components/

**Comment by artola** [comment]
@stepancar Your styleguide customisation is great! ... could you please share it?

**Comment by elevatebart** [comment]
@artola a quick serch in github just in case put me [here](https://github.com/alfa-laboratory/arui-feather/blob/master/styleguide.config.js)

**Comment by artola** [comment]
@elevatebart Thanks a lot!

**Comment by tizmagik** [comment]
@konradk wow that is a really beautiful styleguide -- mind sharing the config/customizations you made for that? I especially like how the sample code is offset to the right column like that. 😍

**Comment by mealeyst** [comment]
I have been slowly migrating our react components to styled components and I am using styleguidist to have easy to view documentation for our components!

https://mealeyst.github.io/mirage/

**Comment by mealeyst** [comment]
I am starting to move our components at our organization over to styled components and I am using styleguidist as our organization's pattern library.

https://rocketsofawesome.github.io/mirage/

**Comment by gazpachu** [comment]
Hiya!,

I've just released `sugUI`, a design system template based on `Styleguidist` that uses the sugUI components library: https://gazpachu.github.io/sugui-design-system/

![](https://gazpachu.github.io/sugui-design-system/img/screenshot.jpg)

**Comment by poteirard** [comment]
In [Zopa](https://www.zopa.com/) we just released our first open source project. Our react-components library using this amazing tool ❤️ Still a lot work to be done but here's our first version :) https://github.com/zopaUK/react-components

<img width="1385" alt="React_components" src="https://user-images.githubusercontent.com/7198934/58337421-077db480-7e46-11e9-8460-ee591acb3611.png">

**Comment by jenniesyip** [comment]
Our design system for Udacity is using Styleguidist! https://veritas.udacity.design/ 

![image](https://user-images.githubusercontent.com/1864971/58583899-dfa59c80-8209-11e9-8635-a4779b2b45f4.png)

**Comment by galhavivi** [comment]
We're using Styleguidist on our open source Form library :)
https://yahoo.github.io/jafar/

![image](https://user-images.githubusercontent.com/10723257/87904433-f4c13880-ca66-11ea-88e6-180d2574b5dc.png)

![image](https://user-images.githubusercontent.com/10723257/87904366-d0655c00-ca66-11ea-83fc-ad36ac9b3086.png)

**Comment by hosseini44444** [comment]
I'm using Styleguidist for building and improvement of my free Slider component for React, named [Slidish][1].

Click here to see the [Slidish][1] documentation built with styleguidist.

[1]: https://hosseini44444.github.io/slidish/
