### ISSUE TITLE
[question] Section feature is not available on latest npm

### ISSUE THREAD

**Issue by AoDev** [sapegin/react-styleguidist#129]
Hello, 

Not sure if the section feature is a work in progress?
Checking the docs, it explains the section feature, but 2.1.0, which is latest from npm, does not have this feature yet.

Could you tell us the status?

**Comment by sapegin** [comment]
There are quite a lot of changes since 2.1.0: 
https://github.com/sapegin/react-styleguidist/compare/2.1.0...master

But I’d like to wait for #124 before a new release.
