### ISSUE TITLE
Exception when having an enum in propTypes

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#13]
(originally reported in https://github.com/sapegin/react-styleguidist/issues/9#issuecomment-145516722)

I can now run styleguidist, and it can display the props for one component, but when I add another one, it fails:

![image](https://cloud.githubusercontent.com/assets/3027415/10279275/92bb7de6-6b64-11e5-8d1a-002fc7921aee.png)

I think it's because of the enum in the other component's `propTypes`. Here are the `propTypes` of the relevant component:

```
    propTypes: {
        issue: React.PropTypes.object,
        width: React.PropTypes.oneOf([26, 40, 55, 70, 110, 155, 190, 265]),
        style: React.PropTypes.object,
    },
```

**Comment by sapegin** [comment]
I can’t reproduce it:

![](http://wow.sapegin.me/image/1u2p0m40413n/Image%202015-10-06%20at%208.43.07%20PM.png)

Maybe there are some other fields like `defaultProps`…

**Comment by mik01aj** [comment]
I don't have `getDefaultProps` in this component. What else is checked?

**Comment by sapegin** [comment]
I don’t know what react-docgen is returning for your component. If you show me the full component code, I could debug it.

**Comment by mik01aj** [comment]
A ha! I got it!
So well, actually my enum was generated from some other data. This is the output from `react-docgen`:

```
{
  "description": "",
  "props": {
    "issue": {
      "type": {
        "name": "object"
      },
      "required": false,
      "description": ""
    },
    "width": {
      "type": {
        "name": "enum",
        "computed": true,
        "value": "_.map(_.keys(coverWidths), _.parseInt)"
      },
      "required": false,
      "description": ""
    },
    "style": {
      "type": {
        "name": "object"
      },
      "required": false,
      "description": ""
    }
  }
}
```

`coverWidths` is a variable defined in that file. In runtime it's generated correctly, but `react-docgen` can't parse it.
