### ISSUE TITLE
Styleguidist not working with npm 2 (error in make-webpack-config.js)

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#131]
The problem is here: https://github.com/sapegin/react-styleguidist/blob/3a7271fc59ada1bcb959d62d174d64fecdc69645/src/make-webpack-config.js#L73

`getPackagePath('entities')` breaks, because `entities` is not a dependency of styleguidist. `entities` is a dependency of `markdown-it`, which is a dependency of styleguidist, so:
* when installed with npm 2, the `entities` module is not accessible from styleguidist,
* when installed with npm 3, the `entities` module is not guaranteed to be always accessible from styleguidist (because if some of other dependencies starts depending on another version of `entities` package, npm 3 will nest them).

@sapegin, could you explain why is the json loader needed there?

Maybe we could change the regex to target specifically these files? Or the other way round, enable it for any `*.json` files?

**Comment by sapegin** [comment]
1. It’s needed because Markdown It uses some JSON files.
2. We shouldn’t enable any loaders that could affect user’s code.

But do we actually need to support npm 2?

As a quick fix we could try to replace `getPackagePath('entities')` with:

```js
[
  getPackagePath('entities'),
  getPackagePath('markdown-it')
]
```

**Comment by mik01aj** [comment]
> But do we actually need to support npm 2?
Yes, because of Node 4.x LTS releases. [They are pretty new and they still use npm 2](https://nodejs.org/en/download/releases/).

And your quick fix will not work, because `getPackagePath('entities')` fails with an exception.

I'm actually surprised that Webpack doesn't support json by default. On the other hand, [it would be nice if `entities` wouldn't require json files](https://github.com/fb55/entities/pull/26)...

For the time being, I propose to just change these lines like so:

               {
					// TODO: remove this then entities module is fixed (https://github.com/fb55/entities/pull/26)
					test: /node_modules\/entities\/.*\.json$/,
					loader: 'json'
				},

**Comment by sapegin** [comment]
Looks good for me.

**Comment by mik01aj** [comment]
> We shouldn’t enable any loaders that could affect user’s code.

On the other hand, we already force users to use ES6+JSX in examples, with Lodash 4 and React 15. Anyone using other versions of these libraries, or other Babel config might have problems with writing practical examples. I think that this is more important then avoiding enabling the json loader for user files.  ;)

As for the fix - I'll make a PR. But I've seen this:

```
function validateWebpackConfig(webpackConfig) {
	webpackConfig.module.loaders.forEach(function(loader) {
		if (!loader.include && !loader.exclude) {
			throw Error('Styleguidist: "include" option is missed for ' + loader.test + ' Webpack loader.');
		}
	});
}
```

Shall I add `include: node_modules` to the laoder then?

**Comment by sapegin** [comment]
> I think that this is more important

But there’s no easy fix if it’s possible to fix at all.

> Shall I add include: node_modules to the loader then?

Yeah, I think so.

**Comment by stepancar** [comment]
@mik01aj, error when i use  2.2.1 and npm 3.8.6
![screenshot_1](https://cloud.githubusercontent.com/assets/2854910/14892661/96ebc760-0d74-11e6-8848-34f136628c3c.jpg)

**Comment by mik01aj** [comment]
Yes, this was already reported in #135.
