### ISSUE TITLE
Images in markdown throw React error

### ISSUE THREAD

**Issue by marklundin** [sapegin/react-styleguidist#140]
Adding `![image](path/to/image.png)` in markdown throws `img is a void element tag and must not have 'children' or use 'props.dangerouslySetInnerHTML'. Check the render method of MDReactComponent.`

I assume this is actually https://github.com/alexkuz/markdown-react-js/issues/5

**Comment by sapegin** [comment]
But they work fine?

We should get rid of `markdown-react-js`: it has lots of issues and it’s dead (no commits since November 2015).

**Comment by marklundin** [comment]
No, nothing renders.

Have you checked http://rexxars.github.io/react-markdown/. Seems to be under active dev and img seems to work
