### ISSUE TITLE
Add HTML rendering support

### ISSUE THREAD

**Issue by marsbergen** [sapegin/react-styleguidist#141]
It would be great if your can put HTML in your Markdown files which will just be rendered, like Markdown can.

**Comment by sapegin** [comment]
Could you please submit a pull request with it?

**Comment by marsbergen** [comment]
Yeah I was thinking about that already, I need it on short term, so sure I'll create a pullrequest when I have something running.

Btw is it correct that > for blockquotes are disabled?

**Comment by sapegin** [comment]
Nope, it must be a bug or just missing styles.

**Comment by sapegin** [comment]
There’s very basic HTML support now: 552507f4a87c455ab26150cc141f3ce715952e59.
