### ISSUE TITLE
Webpack 2 support?

### ISSUE THREAD

**Issue by FezVrasta** [sapegin/react-styleguidist#146]
Could you add support for Webpack 2?

**Comment by sapegin** [comment]
I’m not sure that we can just *add* support. I’m afraid it would be Webpack 1 or Webpack 2. Any help and research is very appreciated because I don’t have any experience with Webpack 2 so far.

**Comment by brandondurham** [comment]
What’s involved here?

**Comment by bulaj** [comment]
it does work just fine on webpack 2 in most common cases for me

**Comment by sapegin** [comment]
@bulaj Great to hear it! Any issues or tips that we can include to the docs?

**Comment by bulaj** [comment]
Well, not really, it just works as intended out of box, no workaround was needed to setup.
We dont do anything fancy with it though, just basic styleguide, so dunno if there are any problems deeper.

**Comment by 2oo** [comment]
Unfortunately it doesn't work with webpack 2.1.0-beta.20. It worked fine with no workarounds until beta.19.
