### ISSUE TITLE
Skipped components cannot be used in examples

### ISSUE THREAD

**Issue by idris** [sapegin/react-styleguidist#153]
I have a component structure where I have a `ProgressStep` component that's only used within a `ProgressStepBar`.  My example looks like this:
<img width="822" alt="screen shot 2016-06-29 at 7 21 19 pm" src="https://cloud.githubusercontent.com/assets/13989/16474805/b13af4f2-3e2e-11e6-84e3-5b12d34dd9f0.png">

However, since this example includes `ProgressStep`, I don't want to document `ProgressStep` separately.  So I set `skipComponentsWithoutExample` to `true`.  Now my example throws an error:
<img width="817" alt="screen shot 2016-06-29 at 7 23 35 pm" src="https://cloud.githubusercontent.com/assets/13989/16474848/032494bc-3e2f-11e6-8501-1e9c0f9ddb62.png">

--

This shouldn't happen.  Even when a component is skipped, it should be able to be used in an example.  Maybe there should be a way to specify imports in examples?

**Comment by sapegin** [comment]
Then we will need a way to really skip components that can’t be loaded by style guide because of HOCs
or something like that.

There is [a way](https://github.com/sapegin/react-styleguidist/blob/master/docs/GettingStarted.md#writing-code-examples) to specify imports in examples.

**Comment by mik01aj** [comment]
Yes, I would say, just `require` your component in the example code.

**Comment by idris** [comment]
Totally missed that I can `require` other components.  Thanks for the quick responses!  Closing this now.
