### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#154]
There are 22 commits since last release. @sapegin, could you publish a new one? (Not sure if minor or major)

**Comment by sapegin** [comment]
Sure. Looks like it could should be major:

Changes that might be breaking:

* Code is hidden by default: 80ab7b8e46b00c433390296439f35f6378bfc9cf (I wouldn’t care about this one).
* Different setState behavior, especially new way of defining default state (`initialState = {count: 1};`): 88de0c20bec18343f11c2294158a390769047498.

**Comment by mik01aj** [comment]
3.0.0 released! 🎉

**Comment by ndelangen** [comment]
Congrats on this major release!

**Comment by sapegin** [comment]
@ndelangen Thanks! :shipit:

**Comment by mik01aj** [comment]
wow, 3.0 is great. There is [a small bug](https://github.com/sapegin/react-styleguidist/issues/155) but the styleguide page now runs so smoothly! Looks like CodeMirror was really heavy resource-wise. Great work! 👍

**Comment by sapegin** [comment]
Thanks to @tizmagik for implementing collapsible examples!

**Comment by tizmagik** [comment]
Nice work on this release guys! Lots of great improvements all around! 😁
