### ISSUE TITLE
propType warnings from valid examples (in 3.0)

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#155]
In this example:

```
initialState = {star: 'wars'};
<Button label={ state.star } />
```

I get a propType warning:

    Required prop `label` was not specified in `Button`

This happens only when the code is run for the first time to determine the initial state (see [`Preview.js`](https://github.com/sapegin/react-styleguidist/blob/88de0c20bec18343f11c2294158a390769047498/src/rsg-components/Preview/Preview.js#L60)). In `render`, all is OK and it works fine.

For now I was able to work around this by adding this to the init code:

    var React = {createElement: _.noop, createClass: _.noop};

But it doesn't seem like a very good solution. 😕

**Comment by mik01aj** [comment]
Maybe this could be fixed by changing the `initCode` to this: 

    const initCode = `
        // Workaround for https://github.com/sapegin/react-styleguidist/issues/155
        var React = {}; // so React.createElement will throw
        var initialState = {};
        try {
            ${compiledCode}
        } catch (e) {
            // ignoring
        } finally {
            __initialStateCB(initialState);
        }
    `;

Note that I assume that `initialState` will be assigned *before* any React elements are created. For my 116 examples it was true.

**Comment by sapegin** [comment]
Looks like it works. I hope it doesn’t break anything ;-|
