### ISSUE TITLE
StyleGuide component can't be used as a wrapper

### ISSUE THREAD

**Issue by benknight** [sapegin/react-styleguidist#156]
From the docs:
 > Also there are two special wrapper components. They do nothing by themselves and were made specifically to be replaced with a custom logic:
>
> * `StyleGuide` — the root component of a style guide React app.
> * `Wrapper` — wraps every example component.

https://github.com/sapegin/react-styleguidist/blob/master/docs/FAQ.md#how-to-change-the-behaviour-of-a-style-guide

Looking at the StyleGuide source, it's not actually a wrapper, as in doesn't just pass it's children on (like the Wrapper component does).  So replacing it actually overrides the entire component tree.

I could get around this issue if I could somehow import the StyleGuide component from the react-styleguide package but I don't think that's possible.

**Comment by sapegin** [comment]
It’s called wrapper because you can use it to wrap style guide in your own markup.

What do you want to achieve? I’ve added an example to the FAQ but it’s not that useful.

**Comment by benknight** [comment]
I was expecting to be able to use it to render the StyleGuide as a child of my own wrapper component, so I can run my own code on `componentDidMount` for example.

**Comment by sapegin** [comment]
What did you try and what didn’t work?

**Comment by benknight** [comment]
I first tried what was recommended in the FAQ section, replacing the StyleGuide component with my own:

```js
webpackConfig.resolve.alias['rsg-components/StyleGuide'] = path.join(__dirname, 'lib/styleguide/StyleGuide');
```

But again the problem I had with this is it overrides the entire component tree inside of this package, when all I'm trying to do is insert of wrapper component of my own at the top so I can do things like execute code on componentDidMount, or define a context variable for instance.  Does that make sense?

**Comment by benknight** [comment]
I think one thing that might be confusing here is I assumed I couldn't import things from rsg-components in my own code, but it appears that I can, for example, in my own `lib/styleguide/StyleGuide`:

```import Layout from 'rsg-components/Layout';```

I didn't think that would work because there is no rsg-components package in node_modules, but apparently I can (I just tried and it worked).  I guess I'm unfamiliar with webpack.  It's odd to me that you can import modules like that.

**Comment by sapegin** [comment]
That’s why I’ve added a new example to the FAQ.

**Comment by benknight** [comment]
Ohhh, I see.  Duh.  Yeah that makes perfect sense.  Thanks.
