### ISSUE TITLE
Any tips for making it run faster?

### ISSUE THREAD

**Issue by benknight** [sapegin/react-styleguidist#158]
Right now it's taking the build command around ~45 seconds to complete.

**Comment by sapegin** [comment]
I think it’s pretty normal for Webpack builds. Feel free to send pull request that makes it faster.

**Comment by mik01aj** [comment]
Btw, @sapegin - as styleguidist is mostly webpack-based, perhaps we could support building/serving like this:

```
// webpack.config.js
module.exports = [
    { ... user webpack config ...},
    require('react-styleguidist').makeWebpackConfig(),
];
```

Then, when you need both "normal" and styleguide server, the whole project code would be built just once.

**Comment by sapegin** [comment]
@mik01aj Are you suggesting merging user site’s Webpack config and Styleguidist’s?

**Comment by mik01aj** [comment]
no, I mean putting them side by side. See http://stackoverflow.com/questions/29640996/webpack-with-an-array-provided-as-config

**Comment by sapegin** [comment]
Nice! If you have time to implement it ;-)
