### ISSUE TITLE
Warning: Element: `ref` is not a prop.

### ISSUE THREAD

**Issue by reintroducing** [sapegin/react-styleguidist#159]
Hey @sapegin, been a while since I looked at this repo but I'm back to working on a SG and it's great to see the progress that has been made here.  I got up and running rather quickly this time around but I'm seeing the following in my console: https://www.dropbox.com/s/o2mvgqhjmpop1iw/Screenshot%202016-07-24%2020.05.37.png?dl=0

I only have one very simple component being written in my SG right now as I wanted to just see everything up and running before I document them all.  When I drill into the error it looks like its coming from Preview.js's render method but I'm not getting much further with the debugging than this.

Any ideas?

**Comment by sapegin** [comment]
I hope I haven’t broken anything ;-)

**Comment by reintroducing** [comment]
Thanks! Does this need a new version published to npm?

**Comment by reintroducing** [comment]
@sapegin Can you publish the newest to npm please?

**Comment by sapegin** [comment]
Done.

**Comment by reintroducing** [comment]
works great, thanks!
