### ISSUE TITLE
Potential case-sensitivity issues

### ISSUE THREAD

**Issue by quietcodes** [sapegin/react-styleguidist#165]
I ran into an issue where the static build was being processed differently locally than it was on our production server. The issue ended up being that my demo files were named `README.md` instead of `Readme.md` and the operating systems handled case-sensitivity differently for the file check. File existence is checked with [fs.existsSync](https://nodejs.org/api/fs.html#fs_fs_existssync_path) which has been deprecated, so there may be a better way available. It would be useful to make a note about the case sensitivity of file names or update the file existence check so it handles case-sensitivity consistently (one way or the other). 

In any case, I thought it would be worth mentioning here in case anyone else runs into the issue, since it was hard to debug. Local dev work was being done on Mac; prod builds were done in a Docker container running Ubuntu.

**Comment by sapegin** [comment]
This issue is not related to Styleguidist but to development in case-insensitive OS (Mac) for case-sensitive OS in production (Ubuntu).

Pull request with a warning would be probably useful.

P. S. There’s nothing wrong with `fs.existsSync`.
