### ISSUE TITLE
Question: detect React Component class instances as React components

### ISSUE THREAD

**Issue by romelperez** [sapegin/react-styleguidist#167]
Hi,

I am using [react-i18next](https://github.com/i18next/react-i18next) to translate my React components. When I generate the style guide this error appears and my components translated are not included:

```bash
Error when parsing src/components/main/Header/index.js
Error: No suitable component definition found.
```

My guess is that the declaration of React components with it:

```js
import React from 'react';
import { translate } from 'react-i18next';

const MyComponent = function () {
  return <div>Component content</div>;
};

export default translate()(MyComponent);
```

is exporting a React Component class instance ([translate function](https://github.com/i18next/react-i18next/blob/master/src/translate.js#L103)) instead of an object as:

```js
import React from 'react';

const MyComponent = function () {
  return <div>Component content</div>;
};

export default MyComponent;
```

Should it work this way? Or maybe I am doing something wrong?

**Comment by sapegin** [comment]
Have you tried the second approach? It should work.

**Comment by romelperez** [comment]
Yes, and I works pretty well, but I can't translate my components with that library which is a good one.

Should I use another?

**Comment by sapegin** [comment]
I’m using React Intl but I have the same issue. And I don’t know how to solve it in generic, convenient and bullet-proof way. So any suggestions are welcome.

**Comment by romelperez** [comment]
My guess is that it have to do with the component detection, because there are some wrappers, like the internationalization ones, that don't export the result as:

```js
<div>Component content</div>
```

For example.

I'll try to figure out what I can do and share it.

**Comment by sapegin** [comment]
Related issue: #143.
