### ISSUE TITLE
Including External CSS

### ISSUE THREAD

**Issue by kevinhos** [sapegin/react-styleguidist#171]
I'm having an issue and wondering if there's a option in the configuration to address it. My component styles are maintained outside of the components and not directly imported by them (dir structure example below). For deploys, the styles are compiled separately and included in the document head.

My issue is: I can't seem to instruct `react-styleguidist` to include them.

I've tried specifying a custom template that points to the built styles; however, all the paths I've tried return a 404 (can't get the path right). If I can get that correct it would be a workable solution. I would lose file watching and reloading though.

Are there any other approaches I should look at?

```
src
 |- components
 |- styles
     |- index.css
```

**Comment by sapegin** [comment]
Have you tried [this solution](https://github.com/sapegin/react-styleguidist/blob/master/docs/FAQ.md#how-to-add-custom-js-and-css)?

**Comment by kevinhos** [comment]
@sapegin that was exactly what I needed. Thanks!

**Comment by chardos** [comment]
Would love to see the solution, link seems to be broken?

**Comment by sapegin** [comment]
@chardos I’ve updated a link.

**Comment by chardos** [comment]
@sapegin That was an incredibly fast response. Thanks man!

**Comment by sapegin** [comment]
@chardos Morning coffee works very well ☕️🚀

**Comment by dchambers** [comment]
Is there a way to import CSS directly into the index page without using a `require` as this doesn't seem to be compatible with the webpack config used by create-react-app?

**Comment by neutraali** [comment]
I might have the same question as @dchambers has... We'd like to include a _local_ CSS -file in the template:  
```html
<link rel="stylesheet" href="<%= process.env.baseUrl %>static/css/all.css" />
```
... This naturally gives a 400 -error and is unable to locate/use the file.

**Comment by usamamashkoor** [comment]
@neutraali did you find a way to include local css in your react app i am facing the same issue here ..?

**Comment by neutraali** [comment]
Hey @usamamashkoor, not with **react-styleguidist** at least. I was only trying to get a quick look on how the lib would work. It didn't - So I quickly moved on to other solutions. :cat:
