### ISSUE TITLE
How to make react-styleguidist support jsx?

### ISSUE THREAD

**Issue by asci** [sapegin/react-styleguidist#175]
I got this error
```
ERROR in ./components/button/button.jsx
Module parse failed: ~/ui-kit/components/button/button.jsx Unexpected token (36:6)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (36:6)
    at Parser.pp$4.raise (~/ui-kit/node_modules/react-styleguidist/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)

```

and on a line `button.jsx:36:6` there is jsx syntax starts.

My `styleguide.config.js` is:
```
module.exports = {
 title: 'My awesome styleguide',
 assetsDir: 'dist',
 template: './styleguide.html',
 components: './components/**/*.jsx',

 getExampleFilename: function(componentPath) {
   return componentPath.replace(/\.jsx?$/,   '.md');
 },

 updateWebpackConfig: function(webpackConfig, env) {
   // Your source files folder or array of folders, should not include node_modules
   webpackConfig.module.loaders.push({
     test: /\.jsx?$/i,
     exclude: /(node_modules)/,
     loader: 'babel'
   });

   return webpackConfig;
 },
};

```

I also know, that default loaders contain react loader, I tried to remove `updateWebpackConfig` no effect. Any ideas?

**Comment by sapegin** [comment]
There’s no such thing as “react loader” and default loaders do not affect your code. 

1. Try to use `include` instead of exclude, like in the docs.
2. Check you Babel config. You should have `react` preset here.

**Comment by asci** [comment]
by "react loader" I mean `babel-loader` with `react` preset.

Thanks, will try

**Comment by asci** [comment]
It is strange, I reverted my changes in the project to commit when it worked. And now it doesn't. Maybe it is somehow related to node\npm\some dependency version or so? Will check again in the evening. The basic example is working well.
