### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by andresgutgon** [sapegin/react-styleguidist#176]
I'm having this error when I add documentation to a method.

``` javascript
const MyComponent = React.createClass({
  /**
   * Manage toggle click
   */
  onClick() {
     // Something here
  },

  render() {
     return (<div onClick={this.onClick} />)
  },
});

export default MyComponent;
```

When I add `Manage toggle click` RDoc comment I get `TypeError: undefined is not a function`. If I remove the comment over `onClick` method webpack compilation is fine.

Any ideas?

**Comment by sapegin** [comment]
Hm, I can’t reproduce it. Trying to copy your code to the example styleguide: works with with or without the comment.

**Comment by andresgutgon** [comment]
Please can you check out this branch. I just converted the component to use `React.createClass` and the error is reproduced with this comment: https://github.com/sapegin/react-styleguidist/pull/177/files#diff-07e392e9ddba72895f1dc7298921c452R32

**Comment by andresgutgon** [comment]
I think the key is using `React.createClass`

**Comment by andresgutgon** [comment]
As commented in the PR the problem is with my node version. You need to use a node version `>= 4.x.x` with `react-styleguidist`.

Thanks @sapegin

**Comment by sapegin** [comment]
Just for the reference, it’s not in the master yet: dccecb0ded66ca2119db5f04d1aefc8bd3024946.
