### ISSUE TITLE
ReferenceError: file is not defined

### ISSUE THREAD

**Issue by ahutchings** [sapegin/react-styleguidist#179]
I'm getting the below reference error when building my project using styleguidist. It looks like the console logging that occurs in the catch block of props.loader.js is referencing a `file` variable that is declared in a different block. This could probably be fixed by initializing `file` as a var outside the `try` block scope.

```
Module build failed: ReferenceError: file is not defined
    at Object.module.exports (<snip>/node_modules/react-styleguidist/loaders/props.loader.js:40:66)
```

```
❯ node -v
v6.5.0
❯ npm -v
3.10.7
❯ cat package.json | grep version
  "version": "3.1.1"
```

**Comment by mik01aj** [comment]
I can't see any scope problems with `file` in [`props.loader.js`](https://github.com/sapegin/react-styleguidist/blob/master/loaders/props.loader.js).

**Comment by ahutchings** [comment]
Ah, I see that this was fixed in #173, but it has not been released to npm yet. Could we publish a new version to npm?

**Comment by masylum** [comment]
Could we have a minor version with that fix in the meantime?

**Comment by sapegin** [comment]
Nope, sorry for inconvenience. But I’ll make a new version this week anyway.

**Comment by sapegin** [comment]
[4.0.0](https://github.com/sapegin/react-styleguidist/releases/tag/4.0.0) is out!
