### ISSUE TITLE
Customize Layout/Features

### ISSUE THREAD

**Issue by nhavar** [sapegin/react-styleguidist#181]
Is there any easy way to customize the layout or add functionality to the guide that I'm missing (other than just forking the whole project and modifying it). 

For example: I want to move the nav to the right and add a scroll spy capability as well as change the order in which documentation appears (i.e. Props, Description, Render, Code to Description, Render, Code, Props.)

EDIT: Nevermind, I didn't dig far enough in.

**Comment by mik01aj** [comment]
You can override the styleguide components as described in the FAQ.

**Comment by nhavar** [comment]
Well... I thought I had a handle on this, but it seems like I'm missing something important.

I have added an alias in the config. 
I have copied over and customized the Layout.js and css.
That works.
Likewise, I did the same with ReactComponent.js
That works.
Tried the same process with Preview.
Didn't work. Still renders default Preview view.
Tried the same process with Playground.
Didn't work. Still renders default Playground view.

What am I missing?

**Comment by sapegin** [comment]
I don’t know ;-) But if you post an example project somewhere I could take a look.

**Comment by nhavar** [comment]
I forked the project and modified customised with a bare-bones example. It should render the preview section with just a paragraph of text and nothing else. Instead, it continues to render the normal Preview of the component unhindered.

https://github.com/nhavar/react-styleguidist/tree/master/examples/customised

**Comment by sapegin** [comment]
There’s no `rsg-components/Preview/Renderer` component, only `rsg-components/Preview`. What do you want to customize there? There’s not much HTML ;-)

Same for `Playground` but I can extract HTML to `Playground/Renderer`.

**Comment by nhavar** [comment]
In general, I need to understand the mechanism of what can/cannot be customized. Are only rsg-components with Renderers customizable? Or can any rsg-component be customized but the mechanism is different (different alias, different js/content structure).

**Comment by sapegin** [comment]
Any .js file in `rsg-components`.

**Comment by nhavar** [comment]
Okay, so I just have the alias setup wrong. Got it. Thank you.
