### ISSUE TITLE
Multiple exported component definitions found

### ISSUE THREAD

**Issue by Alberthoven** [sapegin/react-styleguidist#185]
Hi.

I have written a multiple component file Component.jsx. There are the following components definitions:
```
export class ClassComponent1 extends Component {...}
export class ClassComponent2 extends Component {...}
export const ConstComponent3 = () => ...
export const ConstComponent4 = () => ...
export const ConstComponent5 = () => ...
```
When I try to start styleguidist, it raises an error qith the message 'Multiple exported component definitions found'.

Is there any way to achieve start the style guide generator over these kind of compound components? How?

Thanks!

**Comment by sapegin** [comment]
Extracting each component to a separate file would be the best and the easiest way. 

`resolver` and `handlers` options might also help.

**Comment by Alberthoven** [comment]
Ok, it works using '[resolver](https://github.com/sapegin/react-styleguidist/blob/master/docs/Configuration.md)':
```
module.exports = {
  // ...
  resolver: require('react-docgen').resolver.findAllComponentDefinitions,
};
```
Thanks!
