### ISSUE TITLE
Stateless component default props

### ISSUE THREAD

**Issue by jeans11** [sapegin/react-styleguidist#187]
Hi guys !

Just a question. I have stateless component like this:

```javascript
...
const Foo = ({
  baz = "baz"
}: Props): ReactElement<any> => (
...
)

export default Foo
```
It seems that `baz = "baz"` is not supported :(. Indeed, when I go back to:

```javascript
Foo.defaultProps = {
  baz: "baz",
}
```
it's work !

So, there is a way to handle this behaviour ? (I would like to avoid refacto all my components ^^)

**Comment by sapegin** [comment]
Unfortunately it’s a limitation of react-docgen: https://github.com/reactjs/react-docgen/issues/69

**Comment by josias-r** [comment]
@sapegin You are referring to an issue that has actually been resolved?

```
import React from "react";

export interface ExampleFCProps {
  stringProp?: string;
}

const ExampleFC: React.FC<ExampleFCProps> = ({ stringProp = "default string" }) => {
  return <div>{stringProp}</div>;
};

export default ExampleFC;
```
This should work now, shouldn't it? If so, please reopen the issue...
