### ISSUE TITLE
Proper JSX support in the code editor

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#19]
Try something [like this](https://github.com/timbur/codemirror-jsx).

**Comment by mik01aj** [comment]
+1. It looks ugly :)

![image](https://cloud.githubusercontent.com/assets/3027415/10944432/71cb85a0-8319-11e5-83b6-290f4059a16b.png)

**Comment by sapegin** [comment]
Looks like it doesn’t help much :-(

![](http://wow.sapegin.me/image/3n2I2E0e0a1W/Image%202015-11-05%20at%208.11.13%20AM.png)

**Comment by sapegin** [comment]
I’ve tried these, all of them don’t work:

* https://github.com/timbur/codemirror-jsx/blob/master/jsx.js
* https://github.com/rarous/brackets-jsx/blob/master/main.js
* https://gist.github.com/jquense/265b46c740da4d20a718
* https://github.com/codemirror/CodeMirror/pull/3605

**Comment by sapegin** [comment]
The best I could achieve so far:

![](http://wow.sapegin.me/image/0C0R100J1E0p/Image%202015-11-06%20at%2010.23.50%20PM.png)

**Comment by mik01aj** [comment]
Much better than it was. Thanks :+1:

**Comment by mik01aj** [comment]
Have you tried https://github.com/antimatter15/codemirror-jsx?

And https://github.com/codemirror/CodeMirror/issues/3122 is still open, we might get something useful from there later.

**Comment by sapegin** [comment]
They highlight most of the JSX in one color:

![](http://wow.sapegin.me/image/101U2V1E2r3t/Image%202015-11-10%20at%205.12.06%20PM.png)

But we can apply the same hack with hiding error.

**Comment by sapegin** [comment]
I’m closing it until CodeMirror has proper support.

**Comment by petetnt** [comment]
@sapegin @mik01aj Just pinging you that CodeMirror has proper support as of https://github.com/codemirror/CodeMirror/commit/b3f9487046e37facd64196380ebdd8639efc57b5

**Comment by sapegin** [comment]
@petetnt Cooooooool! Thanks!

**Comment by petetnt** [comment]
Oh yeah forgot to add that https://github.com/codemirror/CodeMirror/issues/3745 tracks the issues the mode still might have (it has gotten some great updates in the past few days too)
