### ISSUE TITLE
4.0.x broke hot module reloading

### ISSUE THREAD

**Issue by aaronjensen** [sapegin/react-styleguidist#193]
On 3.1.1 hot module reloading for stateless functional components worked. On 4.0.0 and 4.0.1 it no longer does for our project.

**Comment by sapegin** [comment]
I can reproduce it but have no idea why. All HMR configuration should be external.

**Comment by aaronjensen** [comment]
@sapegin did you change any components from class components to stateless functional components? stateless functional components cannot reload on their own, they must be wrapped at some point by a class component

**Comment by sapegin** [comment]
I did! Now I’m trying to change them back to classes and it doesn’t help ;-(

**Comment by tizmagik** [comment]
Hm, I'm not sure if that's it because the root component is a proper class component, so it shouldn't be an issue. I can repro this locally too, not sure what happened. It did reload once but subsequent reloads don't happen, very odd.

**Comment by sapegin** [comment]
I can reproduce this too in the example. Will try to find the exact commit that breaks it.

**Comment by sapegin** [comment]
Here is the bad commit: f713a3ee2f0b7da2e78138445b9a015daa10270a. Unfortunately the biggest but not the one where I converted classes to functions.

**Comment by sapegin** [comment]
The only solution I could find is this but I’m not sure it’s better than yours. It’s hack too.

```diff
@ Examples.js:15 @
const Examples = ({ examples }) => {
                         <Playground
                             code={example.content}
                             evalInContext={example.evalInContext}
-                             key={index}
+                             key={Math.random()}
                         />
                     );
                 case 'markdown':
```

**Comment by aaronjensen** [comment]
that seems worse, it'll recreate everything anytime anything is rerendered won't it?

**Comment by sapegin** [comment]
Yeah, I think you’re right. How about 3cf04d13ffdd36c60a2a02129b20bb81bf2db69a? Experimenting with your branch.

**Comment by sapegin** [comment]
Actually I like this approach more: no need to configure anything and performance shouldn’t be a big issue because you’d want to develop component in isolated mode anyway.

**Comment by aaronjensen** [comment]
3cf04d1 looks fine. Which approach are you saying you like more? #200?

**Comment by sapegin** [comment]
@aaronjensen Yeap, #200 and 3cf04d13ffdd36c60a2a02129b20bb81bf2db69a ;-)

**Comment by aaronjensen** [comment]
Awesome. I'll close this and my pull out. Thanks!

**Comment by sapegin** [comment]
Thank you too, the solution is 90% yours! :shipit:
