### ISSUE TITLE
Show whitespace in default prop

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#196]
Now if prop’s default value contains only whitespace it renders invisible. I’m not sure about the best solution but at least we can quote whitespace-only values or render spaces as something like `␣`.

![image 2016-10-12 at 10 31 09 am](https://cloud.githubusercontent.com/assets/70067/19302985/08170402-9067-11e6-91ae-33c906ac2d3b.png)

**Comment by aaronjensen** [comment]
How about quoting always? JSON.stringify essentially.

**Comment by sapegin** [comment]
Wold look to noisy in my opinion. But at least quotes should be graying.
