### ISSUE TITLE
Issue using some module with string ref attribute in styleguide component

### ISSUE THREAD

**Issue by corentinmarc** [sapegin/react-styleguidist#201]
Hello,

First of all thank you very much for your work on this nice project!

Currently, we are facing some issues when using some community react component in the styleguide.
For example 'react-bootstrap' DropdownButton or 'react-custom-scrollbars', it seems these modules are using string ref in their code.
 It's not an issue when the components are in the app, no errors, everything goes well. But when importing these components in styleguide some errors are appearing.

"Uncaught TypeError: Cannot read property 'removeEventListener' of undefined", here after a little check in the librarie code ('react-custom-scrollbars') the undefined object is supposed to be an element retrieved by a ref string attribute.

Any idea about this issue ? 

Thanks.

**Comment by sapegin** [comment]
Please make an example as [described here](../Issue_Template.md).

**Comment by sapegin** [comment]
Closing it for now. Feel free to reopen with more data.
