### ISSUE TITLE
Exception thrown with HOC-Components

### ISSUE THREAD

**Issue by marvinhagemeister** [sapegin/react-styleguidist#202]
We've fallen in love with styleguidist at work and plan on using it in our current react-based project. We've hit one showstopper in combination with [HOC-Components](https://medium.com/@franleplant/react-higher-order-components-in-depth-cf9032ee6c3e#.dgafgyv9j). We get the following exception when working with styleguidist:

```
ReferenceError: MyComponent is not defined
```

Reproducible test case:

```js
// MyComponent.js
import React, { Component } from 'react';

const Enhancer = Composed => class MyHOC extends Component {
  render() {
    return <Composed {...this.props} />;
  }
};

const MyComponent = () => {
  return <h1>Hello</h1>;
};

export default Enhancer(MyComponent);
```

MyComponent.md
```md
React component example:

  <MyComponent />
```

**Comment by sapegin** [comment]
Are you using the latest version? It supposed to be fixed — #143.

**Comment by aaronjensen** [comment]
I can confirm that this does not work as expected.

**Comment by aaronjensen** [comment]
I should also mention that react-docgen appears to be doing its job--props are listed, it's just that styleguidist falls down when trying to reference the component. (not sure why, haven't had a chance to dig in)

**Comment by sapegin** [comment]
Maybe the component name is different? Not sure `--verbose` would show it.

**Comment by aaronjensen** [comment]
Oh, yeah the component name would be `Connect(MyComponent)` in my case. Does it use the component name? I would expect it to use the file name.

**Comment by marvinhagemeister** [comment]
It's definitely the component name. Found out that it works when I change the wrapper class `MyHOC`in this case to the expected component `HOC`.

**Comment by marvinhagemeister** [comment]
@sapegin It should be the latest version, but I'll double check to be sure at work tomorrow.

**Comment by marvinhagemeister** [comment]
Spent a few hours today looking into this issue. `styleguidist` simply checks for the exported name property of the exported module. It doesn't know if this is a high-order function (or high-order class) and returns.

`react-docgen` solves this by building a complete AST-Tree with babylon. Once they've got the tree, they walk down the exported `CallExpression` recursively until they find the last one. The rightmost `CallExpression` is assumed to be the actual component.

**Comment by sapegin** [comment]
Right now it uses component name if it’s available and then falls back to file name or folder name if file name is `index.js`.

Can we access this “rightmost” component? That would be awesome.

**Comment by marvinhagemeister** [comment]
Not without a proper `AST-Tree` :/

**Comment by aaronjensen** [comment]
can docgen's output tell us?

**Comment by sapegin** [comment]
I’m fine to change the order to this:

1. Filename (if `[A-Z]*.js`).
2. Folder name (if `[A-Z]*.js` and file name is `index.js`).
3. Everything we had before (`name`, `displayName`, etc.)

Or we can try this thing — might work too: https://github.com/nerdlabs/react-docgen-displayname-handler

**Comment by sapegin** [comment]
@aaronjensen I believe it can with the plugin I’ve mentioned in the previous comment.

**Comment by marvinhagemeister** [comment]
I'm not sure about filename or folder names being the defaults. What about cases like this: `my-component.js` for `MyComponent`?  The only safe solution is the approach taken by `react-docgen`, in my opinion.

**Comment by sapegin** [comment]
That’s why `[A-Z]*.js` — only `MyComponent` would match. But I’d try that plugin for react-docgen first.
