### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by varya** [sapegin/react-styleguidist#213]
In my project, I try to reuse webpack configuration in styleguidist configuration:

```js
const path = require("path");
const glob = require('glob');

const siteWebpack = require("./webpack.config.js");

module.exports = {
  title: 'Swap.com styleguide',
  components: '../react/components/**/*.jsx',
  updateWebpackConfig(webpackConfig) {
    siteWebpack.module.loaders.forEach(function(loader) {
      webpackConfig.module.loaders.push(loader);
    });
    webpackConfig.module.noParse = siteWebpack.module.noParse;
    siteWebpack.plugins.forEach(function(plugin) {
       webpackConfig.plugins.push(plugin);
    });
    webpackConfig.postcss = siteWebpack.postcss;

    return webpackConfig;
  },
  assetsDir: '../../assets',
  template: './client-src/webpack/styleguide.template.html'
};
```

Also, my webpack configuration has `new webpack.HotModuleReplacementPlugin()` as one of its plugins:

```js
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new ExtractTextPlugin("[name].css"),
    new webpack.optimize.CommonsChunkPlugin({
      name: "base",
      filename: "js/base.js",
      minChunks: 2,
      chunks: ["js/home", "js/items"],
    }),
  ]
```

It comes into the the list of styleguidist's plugins as well. Then, because of that, when it get to hot reloading, I get "Maximum call stack size exceeded" error. I guess it is related to this: https://github.com/webpack/webpack/issues/1583

Is there any suggestion, what should I do to work around? The plugins are array, so I don't see easy way to filter the `HotModuleReplacementPlugin` out. However, I think that reusing webpack configuration is obvious need and many others may face the same problem.

**Comment by varya** [comment]
UPD: I came up with this solution

```
+      if (plugin.constructor.name == 'HotModuleReplacementPlugin') {
+        return;
+      }
+      webpackConfig.plugins.push(plugin);
``

But not sure if you would recommend it to other users.

**Comment by sapegin** [comment]
But why do you need any of this plugins in the styleguide? I see point in loaders reusing but not much for plugins.

**Comment by FezVrasta** [comment]
I'm getting this with a CRA app that worked just fine yesterday :-/
