### ISSUE TITLE
Multiple content files in a section

### ISSUE THREAD

**Issue by n1313** [sapegin/react-styleguidist#216]
In my project, I want to have a complete set of documentation generated with styleguidist. That is, I want to have a section describing my components and a section explaining general stuff like an overview of the project, installation steps, contributing guide and so on. I have no problems with the components part, but I would like some guidance on setting up the "general stuff" part.

Currently, I have a README.md file in the root folder and I include it as `content: './README.md` in my config. It works. Unfortunately, as the project grows, the file gets bigger and it is no longer convenient to have everything in one place. I really like the idea of separating different parts of readme into multiple static files, like INSTALL.md, CONTRIBUTING.md or LICENCE, and ending up with nicely organized sub-sections in the docs, ordered in a logical way (so, README first, INSTALL later, for example).  I was thinking of something like `content: ['./README.md', './INSTALL.md']` with maybe some additional fluff to define sub-section names, or possibly having nested sections.

I don't see a way to achieve this with styleguidist currently. Is there? If not, do you think this might be included in the future versions?

**Comment by sapegin** [comment]
You can use subsections for that but they weren’t documented for some reason. I’ve updated the docs and an example styleguide.
