### ISSUE TITLE
issue when using `window.getComputedStyle` in `componentDidMount`

### ISSUE THREAD

**Issue by chrisdrackett** [sapegin/react-styleguidist#220]
I have a component similar to the following that renders fine in our app, however in the style guide it raises errors on `window.getComputedStyle(this.element).fontSize`. I'm not sure exactly what the bug is, but figured it was worth raising.

```javascript
import React, { Component } from 'react'

export default class Sample extends Component {

  componentDidMount = () => {
    const x = window.getComputedStyle(this.element).fontSize
    console.log(x)
  }

  render() {
    return (
      <div ref={(element) => this.element = element}>
        Test.
      </div>
    )
  }
}
```

**Comment by mittalabhas1** [comment]
Hey @chrisdrackett, I'm facing a similar issue with jquery. I'm using it from the window as `window.$` and it says undefined. Could you point me to how you figured this out?
