### ISSUE TITLE
use @example to import examples

### ISSUE THREAD

**Issue by gravitycode** [sapegin/react-styleguidist#226]
I have seen in rumble-js.charts showcase how they import examples using de comment @example. Im trying to use but this give me a error.

The reference in the code:
`
/**
 * Creates a new layer using specific `width` and `height` at specific `position`. It's useful when
*
 * @example ../docs/examples/Layer.md
 */
`

The output error:
`
Module not found: Error: Can't resolve '"examples'
`
Is this method supported?

**Comment by sapegin** [comment]
Please update to [4.2.3](https://github.com/sapegin/react-styleguidist/releases/tag/v4.2.3), it was broken for some time.

**Comment by gravitycode** [comment]
Its works! Thank you @sapegin :)
