### ISSUE TITLE
component example markdown doesn't render with javascript codeblock

### ISSUE THREAD

**Issue by jameslaneconkling** [sapegin/react-styleguidist#230]
This renders out the component as expected (with option to show code):

    ```
    <Chart
      width="600"
      height="300"
    />
    ```

but this only shows code, and does not render the component:

    ```javascript
    <Chart
      width="600"
      height="300"
    />
    ```

This is pretty minor.  The main reason the latter behavior would be preferable is that text editors can add syntax highlighting to code blocks when the language is specified, but leave it unstyled when the language is not specified.  (probably only worth implementing if the fix would be trivial...)

**Comment by sapegin** [comment]
This is [expected behavior](https://github.com/sapegin/react-styleguidist/blob/master/docs/GettingStarted.md#documenting-components) because just highlighted code is often needed.

**Comment by jameslaneconkling** [comment]
OK, good to know.  Thanks for the response.
