### ISSUE TITLE
4.2.x breaks phantomjs rendering

### ISSUE THREAD

**Issue by n1313** [sapegin/react-styleguidist#231]
I have a setup where I use generated docs as part of my automated testing: I take screenshots of parts of the docs page using phantomjs page.render() and compare them to find any visual regressions. It works in 4.1.0, but breaks when I update to 4.2.x -- my screenshots come back completely white as if the bundle code didn't execute at all, but I don't see any errors in phantomjs output. The same page works perfectly when opened in Chrome. The issue reproduces even if the only thing I'm rendering is a simple markdown file.

Webpack doesn't seem to be affecting the issue, it works in 4.1.0 with both webpack 1.13 and webpack 2.1.0-beta, and doesn't work in 4.2.3 with both webpack 1.13 and webpack 2.1.0-beta. I'm using phantomjs 2.1.1. I suspect the problem might be related to introduction of buble in v4.2.

**Comment by sapegin** [comment]
Yeah, I see the same in my tests. Have no idea why it could happen. Probably because of migration from Babel to Buble. But why there’s no errors?

**Comment by n1313** [comment]
Unfortunately I'm not too familiar with phantomjs and buble, so I have no idea. I tried adding `page.onError`, `page.onConsoleMessage` and `phantom.onError` handlers to my scripts, as internet says, but didn't catch anything. 

I can't imagine this issue affecting many users though, so a possible approach would be to ignore it for now and allow users to choose between buble and babel, and document that using buble comes with certain advantages and disadvantages. What do you think?

**Comment by sapegin** [comment]
It may affect our own tests ;-) That’s what I’m [trying to do too](https://github.com/sapegin/react-styleguidist/blob/master/test/phantom.js).

[Buble](https://buble.surge.sh/guide/) is basically the same thing as Babel but smaller, faster and without configuration. Which makes it better for client-side transpiling. babel-standalone was way too big.

**Comment by n1313** [comment]
Yeah, but it achieves that by throwing away some of the things babel does, which in some rare cases such as this one may result in things mysteriously not working. Anyway, I'm glad that you are able to reproduce the bug, I will roll back to 4.1 for now and will await your decision.

**Comment by sapegin** [comment]
I’ve tried to remove Buble (actually any examples rendering) and it doesn’t help.

**Comment by sapegin** [comment]
If you reinstall dependencies it should work. It was because of an arrow function in on of dependencies.
