### ISSUE TITLE
HTML output from marked is not always valid

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#24]
The following produces invalid HTML:

```
marked.parse('<div>')
```

...and if the HTML is invalid, I get this error in console:

![image](https://cloud.githubusercontent.com/assets/3027415/10944924/baf3be9e-831b-11e5-9fff-37f045774af8.png)

...and all the code examples after the invalid HTML part are broken.

I guess we could either:

a) report this as bug in `marked` (but they could say - well, you give inavlid html in, you get invalid html out - it's a big deal mostly with React)
b) check if the produced HTML is valid and throw an error pointing to the problematic file
c) use some other parser like [`react-markdown`](https://github.com/rexxars/react-markdown)

**Comment by sapegin** [comment]
What’s more important is that it’s invalid Markdown ;-) 

But this commonmark looks very promising, I’ll try it.

**Comment by sapegin** [comment]
Right now HTML is disabled in Markdown, not sure if we need to enable it.

**Comment by mik01aj** [comment]
I think not. Maybe at some point we'll need plain HTML code blocks, but that's a different story.

**Comment by sapegin** [comment]
Then I’ll close this.
