### ISSUE TITLE
Better navigation UI in the styleguide

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#28]
Originally suggested by @reintroducing in #12:

>Ability to somehow group components with a navigation so you can show/hide only what section you want to see

>As for the last item, I think this is pretty important for larger codebases where there are lots of components to be shown. It would be fantastic to have something that functions similar to this:

>http://spothero.com/uniform/#ui/css

I love this idea. My current codebase has around 20 components now, so it's not big, but navigating the page is hard already. I think that it's OK to keep it all on one page, we just need some better navigation. Imho the [Bootstrap documentation](http://getbootstrap.com/components/) is a great example of this.

Possibly related issue that might be useful: https://github.com/react-bootstrap/react-bootstrap/issues/51

This project might be useful too: https://github.com/makotot/react-scrollspy

**Comment by mik01aj** [comment]
Possibly related issue that might be useful: https://github.com/react-bootstrap/react-bootstrap/issues/51

**Comment by sapegin** [comment]
We have 21 and I already started thinking about that too ;-) 

I like how it’s done in Bootstrap. I think we don’t need nesting for the first version, it could be just a list of components with position:fixed with or without scrolling spy.

**Comment by psachs21** [comment]
I achieved this functionality by added metadata support to the examples loader. This allows who ever is writing the examples add custom data which can be used by the app to sort/exclude however they want. Just need to replace 'marked' with 'meta-marked' and change the API usage a smidge.

**Comment by sapegin** [comment]
I also like a search field [like here](http://gaearon.github.io/react-hot-loader/).

**Comment by psachs21** [comment]
With the meta-data support and using your own custom styleguide components, that's entirely doable.

**Comment by sapegin** [comment]
I don’t really understand why we need meta data support for that.

**Comment by psachs21** [comment]
You're right, you don't. I guess just lumped tags into my idea of search.

**Comment by sapegin** [comment]
Of course it could be useful for other things like grouping.

**Comment by psachs21** [comment]
Yes, no doubt about that.

**Comment by mik01aj** [comment]
I think that grouping based on directory structure would be enough while not adding new complexity. And I think it's out of scope of this ticket anyway.

So, who's going to implement it? I think I could try, but not this week.

**Comment by sapegin** [comment]
@mik01aj Agree on both of your points ;-) I’m trying to reduce the number of open bugs now, so can’t start right now too.

**Comment by mik01aj** [comment]
So I tried it, and in the simplest variant it's really simple: https://github.com/lovelybooks/react-styleguidist/commit/c5d486827e37f8081e934c34532a6c4c862c9d52 ;)

**Comment by sapegin** [comment]
Great!

**Comment by mik01aj** [comment]
This is getting more and more important for my codebase, and I think that actually we might need some quick design/prototyping phase for this. The point is, the default styleguide is cool for 5 components, but it's hard to navigate it when there are 20 components, and with 50 it's almost impossible. And it is actually a good practice to have lots of tiny components, so I believe we should support this idea too. I wonder if just a simple side navigation with a search box will be enough for this.

**Comment by sapegin** [comment]
It’s definitely enough for the first version because it’s million times more useful that the navigation we have now ;-)

**Comment by operatino** [comment]
As an option, you can always build some abstraction on top of styleguidist. In example with SourceJS integration https://github.com/sourcejs/sourcejs-react-bundle-example, I combine powerful playground from styleguidist with platform integrated navigation options with search and ability to break components into separate pages.

Also, it's a really nice feature, being able to extract only one component example for focued development and responsive design testing http://sourcejs.com/docs/spec/?clarify=true&sections=1. Clarify interface is also available with styleguidist integration plugin.

Although, it really depends on a project, and in some cases one page with all components is the best approach, this is lacking in SourceJS. I have some plans to do automatic combination of component into single page in future, same as we extract components with Clarify.

**Comment by sapegin** [comment]
There are infinite number of possibilities unfortunately (for tools developers)

All your points are good though ;-)

**Comment by sapegin** [comment]
Looks like this is already done in basic form.
