### ISSUE TITLE
Lists in Markdown look like plain text

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#30]
Readme says it shoud work:

![image](https://cloud.githubusercontent.com/assets/3027415/11065770/6f1650a0-87c5-11e5-8beb-9e0edc795801.png)

but this code:

```
* First
* Second
* third

1. First
2. Second
3. Third
```

renders like this: 

![image](https://cloud.githubusercontent.com/assets/3027415/11065816/b02b6d78-87c5-11e5-8cfd-bb5718fdec68.png)

And even the output HTML doesn't look valid, either:

![image](https://cloud.githubusercontent.com/assets/3027415/11065855/e9ed554e-87c5-11e5-8350-243b22f459cb.png)

**Comment by mik01aj** [comment]
Looks like a bug in Marked: https://github.com/chjj/marked/issues/530

So we just need to fix styles in Styleguidist.

**Comment by sapegin** [comment]
There are two bugs: 

1. Bug in Markdown that puts paragraphs.
2. Bug in Styleguidist that do not have proper styles for bullets. 

The latter should be fixed now. So I’m closing this issue — the former bug will be fixed (hopefully) after some future Marked update.
