### ISSUE TITLE
Possibility to add plain Markdown pages as documentation

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#31]
Right now the structure is very strongly component-oriented. It's a good idea for component libraries, but in real world projects there is a need for overview/explanation pages. Being able to add some introduction, higher-level explanation, documentation of data fetching/processing or just a pile of random snippets of html/jsx would be cool.

Additionally, I'd like to be able to define the order of my pages in generated docs.

**Comment by sapegin** [comment]
That’s useful but right now I have no idea how to implement that.

**Comment by mik01aj** [comment]
It's kind of tricky because right now documentation "chapters" are "components". A component may have some examples in markdown. We have a function to get these filenames, so it's a one way relation.

I was thinking that in a general case, it'd be nice to have a structure like this somewhere:

```
[
{title: 'Overview', docs: 'some/path/README.md'},
{title: 'JsonPreview', component: 'some/path/JsonPreview.jsx'},
{title: 'Avatar', component: 'some/path/Avatar/index.jsx', docs: 'some/path/Avatar/examples.md'},
{title: 'Message', component: 'some/path/Message/index.jsx', docs: 'some/path/Message/examples.md'},
{title: 'ApiClient', docs: 'some/path/ApiClient.md'},
]
```

But there's the question, how to design a config API that would be both easy to use and would let us define these relationships for any structure? Of course it would be a breaking change (semver major), but maybe it's worth it. I'm just thinking aloud. What do you think?

**Comment by sapegin** [comment]
Few things:

1. Do we need to mix components and plain documents in one section?
2. Do we need to “link” to particular components instead of folders of components?

It could be something like this:

```
toc: [
  {title: 'Overview', docs: 'some/path/README.md'},
  {title: 'Components', components: 'path/to/components'},
  {title: 'Big Important Section', docs: [
    // ...
  ]},
],
components: function(config, glob, folder) {
  return glob.sync(config.rootDir + '/' + folder + '/**/*.js').filter(function(module) {
      return /\/[A-Z][a-z]*\.js$/.test(module);
  });
},
```

`toc` config option and `folder` attribute are optional (so it backwards compatible).

**Comment by chrisdrackett** [comment]
I like that layout, seems really flexible and easy to create.

**Comment by mik01aj** [comment]
@sapegin there will be confusion between `components` on top level in config and `components` in each TOC. For your questions:

1. My example referred to the current behaviour. For each component, there is a React component definition (parsed by docgen) and an optional markdown file with examples.
2. I'm not sure but I'd say that's not important, since a list with just one element is still a list :)

Your example seems more complex to me, because in my understanding it is:
```
toc: [
  {title: <string>, docs: <glob-or-list>},
  {title: <string>, components: <path-to-folder-which-will-then-be-passed-to-components-function>},
],
components: function(config, glob, folder) { ... },
```

Whereas in my example I thought about something like:

```
toc: function(config, glob) {
  // if you need custom behaviour, implement it here
  // (@sapegin we could make a good example for a start)
  return [
    // many items like:
    {title: <string>, component: <optional-path-string>, docs: <path-string>},
  ];
},
```

**Comment by operatino** [comment]
As I mentioned in other related issue, the best solution I see is to use some tooling abstractions on top of styleguidist generator, keeping it a specific tools for only components documentation.

For example in [SourceJS](http://sourcejs.com) integration bundle with styleguidist https://github.com/sourcejs/sourcejs-react-bundle-example, you both can get cool generator features for React components + other features of SourceJS platform, which also includes plain MD pages documentation.

**Comment by mik01aj** [comment]
@operatino I don't want to pull SourceJS with all its dependencies (phantomjs, grunt with plugins...) and create all the file structure sourceJS needs just to add markdown pages to my styleguidist-powered styleguide.

**Comment by operatino** [comment]
@mik01aj That's a fair point, but abstraction comes at a price. 

BTW in 0.6.0 Phatomjs is already removed from deps, as all the other heavy deps like JSDom. I also will clean-up all the build tools, so the set-up will be much lighter then in was in 0.5.x.

**Comment by sapegin** [comment]
It’s implemented in a basic form.
