### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#32]
Nice default design is great but ability to customize it for particular project is even better. 

Possible solutions:

1. Replace CSS Modules with regular BEM: users will be able to add custom CSS via Webpack config.
2. Fix CSS Modules class names (remove hash): same as 1 but easier for Styleguidist development.
3. Other solution I don’t know about?

**Comment by mik01aj** [comment]
Or maybe add some classes to the existing elements?

I guess that the users will want to style not only the styleguide headers or prop tables, but also the markdown output (which is not styled by our css modules anyway).

**Comment by sapegin** [comment]
I don’t want to have two sets of classes. But we can add add many classes as needed, we don’t have to use all of them internally ;-)

**Comment by mik01aj** [comment]
I like the change a lot! I already started writing some custom styles for my style guide :)

I'll be picky: why `ReactStyleGuidist` if the name of the project is `react-styleguidist`? Directly "translated" to camelCase it would be `ReactStyleguidist`...

**Comment by sapegin** [comment]
No reason, we can change it ;-)

**Comment by sapegin** [comment]
The next thing is better Markdown rendering. Would be nice to have CSS classes for everything in Markdown instead of using cascade and global classes.

**Comment by mik01aj** [comment]
Yes! :+1:  And I'd like the component and prop descriptions to be rendered as markdown too!

**Comment by sapegin** [comment]
It wasn’t easy. I hope I didn’t make it worse ;-|

**Comment by mik01aj** [comment]
I can do some code review on Monday.

**Comment by sapegin** [comment]
Good, I’ll try it on my project on Monday.
