### ISSUE TITLE
Bad things happen when there are multiple components with the same name

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#33]
Basically, the page breaks because of `key`s here:

	renderComponents() {
		let { highlightTheme, components } = this.props;

		return components.map((component) => {
			return (
				<ReactComponent highlightTheme={highlightTheme} component={component} key={component.name}/>
			);
		});
	}

I think we could detect it in `styleguide.loader.js` and then either fix it (`component #1`, `component #2`, etc) or throw an error with some friendly message.

**Comment by sapegin** [comment]
Or we can just append component path to key.

**Comment by mik01aj** [comment]
And later, when we add ids like I did in https://github.com/lovelybooks/react-styleguidist/commit/bb024de001526dcbd7c8befa82ab42d54357152d, shall we also use them for the navigation? (I mean `relativePath`)

**Comment by sapegin** [comment]
Yeah, I think so.
