### ISSUE TITLE
Generating a test based on source examples

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#34]
It would be cool if we could have a task to run all the code examples from the docs and check that they don't throw exceptions both when used with `ReactDOM.render` and `ReactDOMServer.renderToString`. I'd like to put it in  `npm test` task for my project and have it checked with CI.

We just need to get the examples using `examples.loader`, and do it for all the `code` chunks.

I would even implement it myself, but I can't figure out how. I thought I could write something similar to [mocha-loader](https://github.com/webpack/mocha-loader/blob/master/index.js), but I just don't get what's going on there (it's a [pitch loader](https://github.com/webpack/webpack/issues/360), whatever that really means).

Or maybe [enhanced-require](https://github.com/webpack/enhanced-require) (unmaintained :disappointed:) in Node would help? I have no idea.

[Webpack docs about usage in Node.js](http://webpack.github.io/docs/node.js-api.html) might be useful.

I do not argue that we need a feature like this in react-styleguidist, but I'd like to have this for my project, and imho having a recipe how to do this could be also useful for others.

**Comment by mik01aj** [comment]
I tried to build something, but I had to stop [here](https://github.com/istarkov/babel-plugin-webpack-loaders/issues/98).

**Comment by mik01aj** [comment]
But leaving that bug aside, I was able to run a test for one component using this code:

```
require('testdom')('<html><body></body></html>');

var React = require('react');
var TestUtils = require('react-addons-test-utils');
var _ = require('lodash');
var babel = require('babel-core');
var babelConfig = require('./package.json').babel;

global.React = React; // needed for all examples

describe('Button', function() {

    global.Button = require('./ui/Button');
    // var markdownContent = require('./ui/Button/examples.md');
    var markdownContent = require('./examples'); // because of https://github.com/istarkov/babel-plugin-webpack-loaders/issues/98
    var codeChunks = _.filter(markdownContent, {type: 'code'});

    _.forEach(codeChunks, (chunk, index) => {

        it(`should work as in example ${index}`, function () {
            var transformedCode = babel.transform(chunk.content, babelConfig).code;
            var vDom = chunk.evalInContext(transformedCode, _.noop); // noop for setState
            TestUtils.renderIntoDocument(vDom);
        });

    });
});
```

**Comment by mik01aj** [comment]
@sapegin I made some more progress, but I need to change one thing in styleguidist: instead of:

     require('styleguide!')

we would do:

      require('styleguide!' + pathToConfigFile)

Then it would be possible to reuse that loader. Otherwise it always looks for the config path in `process.argv`...

**Comment by sapegin** [comment]
@mik01aj You have push access ;-) I’ll make a new release.

**Comment by mik01aj** [comment]
@sapegin I tried, but it's difficult because the config is needed pretty much everywhere. I believe it should be passed explicitly to every "part", rather than `required` by each module. I could add a flag to override the logic of finding and loading the config, but this feels ugly.

![screenshot 2016-06-06 09 37 41](https://cloud.githubusercontent.com/assets/3027415/15815004/61b8e248-2bca-11e6-9682-3a4528b507b6.png)

**Comment by mik01aj** [comment]
Maybe the `server` and `build` could call some `config.init(argv)` at the beginning. I don't see any better way since we need to pass the config to other loaders too (like `props.loader`), and we even can't serialize the config because it contains JS functions.

**Comment by sapegin** [comment]
That’s difficult but important task. But I’m still not sure about the best (or at least good) way to solve it. 

Passing the config (not just a file path) explicitly would be the best but seems impossible with loaders. But we can start with just a file name, it’s better than nothing anyway.

**Comment by mik01aj** [comment]
@sapegin please have a look at https://github.com/sapegin/react-styleguidist/commit/a4e9cf2565ac67972157e4e6de14370fd25bb6a1. This is the simple solution (not a nice one)

**Comment by sapegin** [comment]
Better than nothing, don’t know how to improve it ;-)

**Comment by mik01aj** [comment]
So I added one more commit and finally got it working.

https://gist.github.com/mik01aj/5b0be7da5453b84a8a2a51b57611c2c7

**Comment by mik01aj** [comment]
So, to sum up, I was able to setup the code for my project (code in [gist](https://gist.github.com/mik01aj/5b0be7da5453b84a8a2a51b57611c2c7)) but it's hacky as it uses some undocumented APIs (setting globals manually, `chunk.evalInContext`, `component.nameFallbak` typo, etc). If more people want it, we could refactor styleguidist so that it's easier to do this kind of tests.

**Comment by sapegin** [comment]
Cool! I’d suggest to close it now until anyone wants more.

**Comment by mik01aj** [comment]
FYI: I updated my gist for v3.0.

**Comment by sapegin** [comment]
I’m working on Node API and thinking about removing this hack. But I want to preserve functionality you need. Check #183 for details.
