### ISSUE TITLE
Add docs about using require() in examples.

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#40]
https://github.com/sapegin/react-styleguidist/pull/25 was merged, but I forgot to add the related documentation. TODO :)

Draft:

---

# Writing usage examples

The examples are extracted from markdown code blocks. They can use any components defined on the page (all the components are exposed as global variables) without requiring them. If you need anything else, you can `require` it just like you would in an ordinary `.js` file. Here's a markdown example:

    Simple example:

        <Message data={ {content: 'Hello world'} } />

    More complex example:

        var mockData = require('./mocks');
        <Message data={ {content: 'Hello world'} } />
    
Note that for mock data, it's often a good idea to use the same mocks in the unit tests too.

If you need more complex demos, you can even use `React.createClass` right in your code examples, but it's often a good idea to define them in a separate `MyComponentDemo.js` file instead and then just require them in markdown.

**Comment by sapegin** [comment]
:+1:

**Comment by mik01aj** [comment]
We'll need to say that all the components are exported to global variables (https://github.com/sapegin/react-styleguidist/blob/master/src/index.js#L18) and that many components have the same name, it will cause problems (or maybe let's throw an error instead? https://github.com/sapegin/react-styleguidist/issues/33)

**Comment by sapegin** [comment]
We can throw an error and suggest to ignore the component.

**Comment by sapegin** [comment]
I’ve added an example component that uses require(). Could you add this docs to the Readme?

**Comment by mik01aj** [comment]
LGTM, sorry @sapegin I didn't find time for this.

**Comment by sapegin** [comment]
No worries ;-) I’m going to release 1.3 soon (I hope before my vacation that star), so I’m trying to add missing docs before that.

BTW, will you have time for #28 soon? I’d like to have it in 1.4.

**Comment by mik01aj** [comment]
This week I'm busy with other (non-react) stuff... I recommend that you just cherry-pick https://github.com/lovelybooks/react-styleguidist/commit/bb024de001526dcbd7c8befa82ab42d54357152d for now.

**Comment by sapegin** [comment]
Thanks, I already have a sticky sidebar, so I can just copypaste an actual TOC code from your commit ;-)
