### ISSUE TITLE
Problem with webpack components alias

### ISSUE THREAD

**Issue by sunesimonsen** [sapegin/react-styleguidist#42]
Hi this is more a question than a issue. I'm trying to use react-styleguidist on a project that as a webpack alias for `components`, that seems to class with react-styleguidist that is also loading things from `components` as well: `import Layout from 'components/Layout'`

Do you know a way around this problem?

Kind regards
Sune

**Comment by sapegin** [comment]
I think I should use something like `react-styleguidist/components` instead.

**Comment by sunesimonsen** [comment]
That would make my life easier, thanks for the awesome software by the way.

**Comment by mik01aj** [comment]
and why not `import Layout from '../Layout'`?

**Comment by operatino** [comment]
Imho without aliases is better, IDE's also help to resolve relative deps in `import`  and `require`.

**Comment by sapegin** [comment]
@mik01aj I couldn’t make aliases work with relative paths. For [components overriding](https://github.com/sapegin/react-styleguidist/issues/12#issuecomment-151879901).
