### ISSUE TITLE
Upgrade to the latest react-docgen

### ISSUE THREAD

**Issue by sunesimonsen** [sapegin/react-styleguidist#44]
The latest version of react-docgen supports React stateless components, it would be really nice if they was also supported by react-styleguidist:

https://github.com/reactjs/react-docgen/commits/v2.4.0

I tested the new version on our style guide and it works great.

**Comment by sapegin** [comment]
Thanks, I’ll do that. Pull request would be even better ;-)

**Comment by sunesimonsen** [comment]
I'll do that :-)
