### ISSUE TITLE
More advanced examples for our sample styleguide (stateful demo components, external mocks)

### ISSUE THREAD

**Issue by sunesimonsen** [sapegin/react-styleguidist#45]
I have a modal that I would like to showcase, but it need to be closed from the beginning. I created a hack to support this, but it would be really nice if react-styleguidist would support something similar out of the box:
```js
<State>
{(state, setState) => 
  <div>
    <Button onClick={() => setState({ isOpen: !state.isOpen })}>Open modal</Button>
    <Modal isOpen={state.isOpen} onClick={() => setState({ isOpen: false })}>Modal content</Modal>
  </div>
}
</State>
```

**Comment by mik01aj** [comment]
Imho it's fine what you did. I have even more complex examples in my styleguide. And if they get really big you can move the example to a separate jsx file and `require` it from the examples md file.

**Comment by sunesimonsen** [comment]
@mik01aj maybe you are right that this should just live in the examples.

**Comment by sapegin** [comment]
@mik01aj Would be nice to see your styleguide. Ours is quite simple so far.

**Comment by mik01aj** [comment]
Okay, so the TODO here is: add more advanced examples to our sample style guide.

**Comment by sapegin** [comment]
@mik01aj :+1: :shipit:

**Comment by sapegin** [comment]
I was trying to find a simpler way to do what you want but couldn’t so I’ve added state to examples:

![](http://wow.sapegin.me/image/2C2t270m1t0v/Screen%20Recording%202015-11-27%20at%2008.19%20AM.gif)

I’ll add an example and docs later.

**Comment by mik01aj** [comment]
That's cool! :+1: 

I understand that the default state is `{}`, right?

**Comment by sapegin** [comment]
Yes. I’m not sure whether we need a way to define the default state and how to do that. Right now you can do something like this:

```js
'prop' in state || setState({prop: 42});
```

**Comment by mik01aj** [comment]
`{}` is fine, I believe. Just don't forget to document it :)

**Comment by sunesimonsen** [comment]
@sapegin the state access is exactly what I want. We made our own solution, but we will switch to this when it is available. Thanks.

**Comment by sapegin** [comment]
:+1:

**Comment by sunesimonsen** [comment]
This is great, when do you plan to do a new release?

**Comment by sapegin** [comment]
In the next few days.

**Comment by sunesimonsen** [comment]
Awesome, looking forward to it.

**Comment by sapegin** [comment]
@sunesimonsen It’s here! ;-)

**Comment by sunesimonsen** [comment]
Awesome thanks for letting me know.
