### ISSUE TITLE
FAQ for the Readme: any questions?

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#47]
I will start it here, please post some useful questions/answers that you already have answered when using styleguidist. We can move them to the README when we have more of them.

If you believe that this should not be a FAQ and would better be merged into the main documentation, please comment. :)

Here's one from me:

> **How can I debug code of my examples?**
Just open your developer tools and type `debugger;` in your code example.

**Comment by mik01aj** [comment]
Maybe it would be better to actually integrate it with the example styleguide, so that anyone can see how it works ;)

**Comment by mik01aj** [comment]
One more:

> **But how do I debug the exceptions thrown from my components?**
> Almost the same way. Put `debugger;` at the beginning of your code and then click the ![screenshot 2015-11-20 09 12 08](https://cloud.githubusercontent.com/assets/3027415/11294827/cbedcea4-8f66-11e5-931a-2730251d2802.png) button to make the debugger stop execution on any exception, continue, and voilà, you got your exception with all the context.

**Comment by mik01aj** [comment]
@sapegin, what do you think about "similar projects" link section? I'd list at least 2:

* https://github.com/insin/react-heatpack#readme
* https://github.com/jaredly/demobox

**Comment by sapegin** [comment]
Great idea especially if the have a single line descriptions not just links. There’s also Source-compatible fork for the Styleguidist — https://github.com/sourcejs/sourcejs-react-styleguidist.

**Comment by mik01aj** [comment]
okay! see my edited comment above.

**Comment by sapegin** [comment]
Coooool!

**Comment by sapegin** [comment]
@mik01aj I’ve added a FAQ (merged your two questions in one) and a list of similar projects. Would cool if you could proofread it.

**Comment by mik01aj** [comment]
@sapegin thank you, I couldn't find time for this.

The debugger instruction, however, is wrong, because you should put `debugger;` first (so that the execution is stopped at the beginning of your example code) and **then** you press ![screenshot 2015-11-20 09 12 08](https://cloud.githubusercontent.com/assets/3027415/11294827/cbedcea4-8f66-11e5-931a-2730251d2802.png), so that when you continue the code execution with 
![image](https://cloud.githubusercontent.com/assets/3027415/11436627/c1f93ea8-94e6-11e5-87e4-883507fd3f6a.png), the execution will be stopped again wherever the exception is thrown.

And I put 2 short questions for a reason: one is for stepping through execution of example code (useful if they contain some logic), and the second was about finding exceptions.

**Comment by sapegin** [comment]
Sorry it wasn’t obvious ;-|

**Comment by sapegin** [comment]
I’ve just noticed that lodash is available in examples. Worth noting that somewhere in the Readme.

**Comment by mik01aj** [comment]
:+1:
