### ISSUE TITLE
sanitize.css breaks components' styles - let's get rid of it

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#49]
![image](https://cloud.githubusercontent.com/assets/3027415/11243210/0a8cd012-8e07-11e5-8062-89bd6a344482.png)

The `background-color: inherit;` breaks stuff for me, because my styles expect stuff to be transparent by default (so that the parent `background-image` is visible).

In general, while rules like this would be ok for a newly-starting product, they are not acceptable for a library that should interoperate with other existing styles.

Related: https://github.com/10up/sanitize.css/issues/43. Maybe upgrading sanitize.css to 2.1 would quick-fix this?

EDIT: but wait... we already have `"sanitize.css": "3.0.0"` in package.json... I don't understand why this rule is still there.

**Comment by mik01aj** [comment]
I got it. My project has `"react-styleguidist": "^0.1.8"` in package.json. Upgrade fixed this.

**Comment by sapegin** [comment]
Styleguidist styles isolation is related to theming and I don’t have a good solution yet.

**Comment by sapegin** [comment]
And I removed sanitize.css ;-)
