### ISSUE TITLE
Add more examples to the example style guide

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#53]
Current examples are too simple.

* [x] `require()` usage.
* [x] `state` and `setState` usage — #45 

Any other ideas?

/cc @mik01aj @sunesimonsen @panayi @reintroducing

**Comment by panayi** [comment]
Perhaps a more advanced example that shows how to switch between themes (dark, light, etc.). 

Each presentational component (`Button`, `Dropdown` etc) is wrapped inside a `Theme` component. `Theme` passes the current theme in [this.context.theme](https://facebook.github.io/react/docs/context.html) to children components.  `ThemeSelector` is used for selecting the current `theme`.

```jsx
/* Theme.md */

Nothing to demo here. Use <ThemeSelector /> to select a theme.
```

```jsx
/* ThemeSelector.md */

<ThemeSelector theme="dark" />
<ThemeSelector theme="light" />
```

```jsx
/* Button.md */

<Theme>
   <Button>Click me!</Button>
</Theme>
```

**Comment by sapegin** [comment]
@panayi Interesting, thanks! Could you point me to some examples of this technique ~~where I could steal the code~~?

**Comment by panayi** [comment]
@sapegin [material-ui](https://github.com/callemall/material-ui) is using `context` for passing the theme. See http://www.material-ui.com/#/customization/themes.

I'm doing something similar, however I'm using redux. What I do:
- Define variables for each theme: `themes/dark.js`, `themes/light.js`
- `Theme` reads the current `theme`. This is where I use redux - it grabs it from the store state. Perhaps make it a global variable, or what else? 
- `ThemeSelector` button: `onClick` set the current `theme` to the property passed to it.
- Presentational components update their styles based on `this.context.theme`.

**Comment by sapegin** [comment]
@panayi Thanks, I’ll try to make something ;-)

**Comment by pke** [comment]
@panayi
> Presentational components update their styles based on this.context.themeVariables

How are those components aware of context changes? Does context change trigger a whole re-render?
