### ISSUE TITLE
Suggestion: Support Array rootDir

### ISSUE THREAD

**Issue by panayi** [sapegin/react-styleguidist#54]
```javascript
module.exports = {
  rootDir: ['./src', './node_modules/material-ui/lib', /* ... */],
  // ...
};
```

This way it becomes easy to use 3rd party components in examples.

**Comment by mik01aj** [comment]
I'll show you what I use (well, actually it's for `components`, but I guess it will solve your problem too) :)

    components: './scripts/{' + [
        'mobilePages/[A-Z]*',
        'ui/BookCoverBox',
        'ui/BookDetails',
        'ui/Button',
        'ui/Avatar',
        'ui/Rating',
        'ui/Review',
        'ui/ShareButton',
        // 'ui/[A-Z]*',
        // 'ui/developerUtils/[A-Z]*',
        // 'ui/Lottery/[A-Z]*',
        // 'ui/selectBoxes/[A-Z]*',
    ].join(',') + '}/index.jsx',

**Comment by mik01aj** [comment]
@panayi did this solve your problem?

**Comment by panayi** [comment]
@mik01aj yes this works great. Thanks!
