### ISSUE TITLE
Document extending Webpack configuration

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#56]
How to add loaders, existing loaders, etc.

**Comment by mik01aj** [comment]
:+1: I'd add one more related thing to think about: how should one integrate a project using webpack with styleguidist? How about project using babel? It would be cool to move these 2 to peerDependencies and thus make styleguidist less of a standalone and more of a tool that integrates tightly with the existing project config.

**Comment by sapegin** [comment]
Yeah, you’re right probably :-)

**Comment by mik01aj** [comment]
@sapegin Maybe let's plan this for 2.0 (whenever it might be)?

**Comment by sapegin** [comment]
Writing an issue right now ;-)
