### ISSUE TITLE
Webpack loaders conflicts 

### ISSUE THREAD

**Issue by okonet** [sapegin/react-styleguidist#57]
If the project already has rules with loaders defined in webpack config, they might conflict with loaders  from styleguidist (CSS and JSON loaders for instance).

I'd suggest to keep the styleguidist webpack config minimal and extend the project's webpack config, adding only loaders required for styleguidist to work properly.

**Comment by sapegin** [comment]
It is minimal ;-) But we need to `include` only the necessary folders. 

But more difficult question: should we enable JS loader for project’s code by default?

**Comment by okonet** [comment]
For instance this

```
{
    test: /\.css$/,
    include: includes,
    loader: ExtractTextPlugin.extract('style', cssLoader)
}
```

might and will affect project's CSS pipeline (which also might have different set of postcss plugins etc.)

But react-styleguidist needs its own CSS pipeline, so I think it should be limited to only its own styles and not make any assumptions about userland css processing.

JS loaders: same issues here. In my setup everything works fine since I also use Babel, but this can break for others. I'm not sure yet if JS loaders used now is cruicial for react-styleguidist to work tho.

**Comment by okonet** [comment]
I also have issues with this one

```
{
						test: /\.json$/,
						loader: 'json'
					},
```

since I'm using `require(json!myJSONFile.json)` in my code.

**Comment by sapegin** [comment]
[2.0.0-rc4](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0-rc4) should fix all this problems.

**Comment by sapegin** [comment]
Closing this for now. Feel free to reopen if you still have this issue.
