### ISSUE TITLE
Existing babel-plugin-react-transform causing errors

### ISSUE THREAD

**Issue by okonet** [sapegin/react-styleguidist#58]
If existing project's `.babelrc` already uses `babel-plugin-react-transform` when it will throuw following error:

```
ERROR in ./~/react-styleguidist/src/index.js
Module build failed: ReferenceError: The plugin "babel-plugin-react-transform" collides with another of the same name
```

This can be fixed by setting `BABEL_ENV ` for instance to `BABEL_ENV=styleguidist` in `package.json`. But I think this can be handled by this package itself. I'll try to submit a PR soon. 

```diff
-"styleguide-server": "styleguidist server",
+"styleguide-server": "BABEL_ENV=styleguidist styleguidist server",
```

**Comment by sapegin** [comment]
Yeah, it’s not cool to ask users to do that ;-)

**Comment by sapegin** [comment]
Other solution could be (in `make-webpack-config.js`):

```
process.env.BABEL_ENV = 'styleguidist';
```

**Comment by okonet** [comment]
Yes, I was also thinking of this.
