### ISSUE TITLE
Adding webpack loader requires hack

### ISSUE THREAD

**Issue by tp** [sapegin/react-styleguidist#6]
I needed to add the `json-loader` because the `color` npm package imports some JSON config files and those break web pack without it.

In order to get this working with `styleguidist` I had to move the `colors` package to `node_modules/react-styleguidist/node_modules` though..

This is how I configure webpack:

```
  updateWebpackConfig: function(webpackConfig, env) {
    webpackConfig.module = webpackConfig.module || {};
    webpackConfig.module.loaders = webpackConfig.module.loaders || [];
    webpackConfig.module.loaders.push({ test: /\.json$/, loader: 'json-loader' });

    return webpackConfig;
  },
```

There seems to be a path issue with require in this project.

**Comment by sapegin** [comment]
Yeah, I think I know how to fix it.

**Comment by sapegin** [comment]
Please try with 0.1.4.

**Comment by tp** [comment]
:+1: Thanks a lot, it works now. Now that the basis is stable I hope to contribute some enhancements!

**Comment by sapegin** [comment]
Great to hear it!

:shipit:
