### ISSUE TITLE
User components are being processed by the react-styleguidist loaders

### ISSUE THREAD

**Issue by sunesimonsen** [sapegin/react-styleguidist#62]
I found that my components are being styled by the react-styleguidist postcss loader, which is suboptimal, as my project also uses CSS modules with other capabilities than the ones supplied by react-styleguidist. @sapegin seems to agree: https://github.com/sapegin/react-styleguidist/pull/60#issuecomment-163391103

Ideally I would like react-styleguidist not to use any kind of special loaders for my components. Right now  `.js`, `.jsx`, `.css` and `.json` files are going through the react-styleguidist loaders : https://github.com/sapegin/react-styleguidist/blob/master/src/make-webpack-config.js#L145-L185
I no that this is more controversial wish, but if you don't agree it would be nice to be able to disabled that using a configuration.

Kind regards
Sune

**Comment by sapegin** [comment]
I’m closing this issue because that’s what we plan to do in the future, see #64 for details. And pull requests are welcome ;-)
