### ISSUE TITLE
ReferenceError: Can't find variable from example (problem with component displayName, "ProxyClass" is used)

### ISSUE THREAD

**Issue by chrisdrackett** [sapegin/react-styleguidist#63]
I'm trying to get up and running and I think I'm getting pretty close. However I'm having an issue with my first component. I'm using a file called `Button.jsx` that has a `const Button = React.createClass({` and `export default Button;` at the bottom. I have styleguidist setup like so:

    rootDir: './src',
    components: './components/**/*.jsx',
    skipComponentsWithoutExample: true,
    getExampleFilename: function(componentpath) {
        return componentpath.replace(/\.jsx?$/, '.examples.md');
    }

when I view the style guide I see `ProxyClass` where I would expect `Button` then in my example I get:

`ReferenceError: Can't find variable: Button`

all the docs from the file are fine and the example code is there and looking ok, just no preview or component name.

**Comment by chrisdrackett** [comment]
also strange, I just added a second component (by adding an example for it) but I don't see it in the listing even after restarting the server. I wonder if it also is coming in as `ProxyClass` so I'm only seeing one thing in the style guide?

**Comment by mik01aj** [comment]
did you try explicitly adding `displayName: 'Button'` in your component?

**Comment by chrisdrackett** [comment]
nope, I'll give that a try. I didn't see that in the examples, but not sure what I'm doing differently. Does it work in the examples because components are in folders?

**Comment by chrisdrackett** [comment]
yep, this fixes things

**Comment by mik01aj** [comment]
I don't know what exactly you do differently, but if you see `ProxyClass` this means that there is some problem with figuring out the name of your component. And if I'm right, the workaround with `displayName: 'Button'` should work. AFAIK file names have currently nothing to do with it (maybe they should, btw).

Still note that what I'm saying is only a workaround and we should still fix the underlying bug or at least provide some friendly error message.

**Comment by chrisdrackett** [comment]
no worries! I'm happy to help debug where I can. I'm primarily a designer so my javascript knowledge isn't as deep as it could be.

**Comment by mik01aj** [comment]
okay, so if adding `displayName` helps, then you should check your babel settings, in particular check whether you have [`babel-plugin-react-display-name`](https://www.npmjs.com/package/babel-plugin-react-display-name) properly configured.

@sapegin, should configuring this be the responsibility of styleguidist (makeWebpackConfig) or the user config?

**Comment by chrisdrackett** [comment]
I didn't see anything about that plugin in the setup or the example project, but maybe I'm missing where its defined.

**Comment by sapegin** [comment]
It’s explained [here](https://github.com/sapegin/react-styleguidist/issues/18#issuecomment-157777618).

**Comment by mik01aj** [comment]
2: So let's do it! Do you think it's better to try to detect the name ([like I did someday](https://github.com/lovelybooks/react-styleguidist/commit/86dd878785b364ce75a57252674abe16bde62f0a)), or to throw an `Error`?

**Comment by chrisdrackett** [comment]
so I'm guessing that my error is that I'm using an older version of babel? I'll try updating and see if that helps.

**Comment by mik01aj** [comment]
No, I don't think so. And styleguidist is using the old (5) version anyway.

Could you post your class definition? (I mean the lines around `React.createClass` or `class ... extends Component`).

**Comment by chrisdrackett** [comment]
`const Button = React.createClass({`

and then

`export default Button;` at the bottom

**Comment by mik01aj** [comment]
Hmm, so, as [you can see in the Babel REPL](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=%0Aconst%20Button%20%3D%20React.createClass(%7B%0A%20%20render%3A%20()%20%3D%3E%20%3Cdiv%20%2F%3E%0A%7D)%3B%0A%0Aexport%20default%20Button%3B), this should add the displayName. Maybe you could check if the `displayName` is really added in your webpack output?

**Comment by chrisdrackett** [comment]
so when I build the styleguide I see display names:

    Button=_react2["default"].createClass({displayName:"Button"

but when running npm run styleguide-server I get the following for button (from the top of the component):

    ProxyClass
    components/Button.jsx
 
and from the console:

    var Button = _wrapComponent('_$Unknown')(_react2['default'].createClass({\n\n  propTypes:

**Comment by mik01aj** [comment]
I think I got it. It's https://github.com/gaearon/babel-plugin-react-transform/issues/19...

**Comment by sapegin** [comment]
I’ll try to add `["react-transform:after"]`. `babel-plugin-react-display-name` is loaded from `babel-core`.

**Comment by mik01aj** [comment]
Looks like [this will be fixed with the next Babel release](https://github.com/gaearon/babel-plugin-react-transform/issues/67). We would just need to update to Babel 6...

**Comment by jardakotesovec** [comment]
Is there some workaround until its fixed? Except put displayName everywhere..

**Comment by sapegin** [comment]
Don’t know. Can anyone try to update to Babel 6 and check and/or send PR?

**Comment by sapegin** [comment]
Please try [2.0.0-rc](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0-rc) with Babel 6.

**Comment by sapegin** [comment]
Feel free to reopen if you still have this issue.
