### ISSUE TITLE
2.0

### ISSUE THREAD

**Issue by sapegin** [sapegin/react-styleguidist#64]
**:boom: [2.0.0](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0) is out. :boom: **

There are some breaking changes planned (or needs discussion) for the next release:

* [x] Disable all Webpack loaders for project’s code by default (#57, #60, #62).
* [x] Show warning when project uses different version of Webpack or Babel.
* [x] Render fenced blocks with language flag as regular Markdown code snippets.
* [x] Fallback to file name or folder name if component name can’t be detected in runtime (#74, #84).
* [x] Update docs.

Removed or postponed items:

* ~~Use custom Babel environment (#58)~~ — now we don’t read user’s `.babelrc` which should fix the problem.
* ~~Move Webpack and Babel to peerDependencies (#56, #61)~~ — see discussion below.
* ~~Make it work with npm 2 (#55, #59, #66).~~ — was fixed before 2.0.
* Use react-docgen to find components (#37) — non-breaking change, can be done later.

**Comment by mik01aj** [comment]
> Move Webpack and Babel to peerDependencies (#56, #61).

I'd add: ...and use existing `webpack.config.js` and `.babelrc` (or `babel` config in `package.json`) by default.

**Comment by sapegin** [comment]
`.babelrc` should be used now (now way to disable it as far as I know).

But using `webpack.config.js` is more complicated and I’m not sure we should do it. I’m afraid it will cause more problems than fixes.

**Comment by okonet** [comment]
I think most poeple who are using webpack have custom pipelines for non-js files. It should be easier tointegrate them with styleguidist config. This is why I also think that project-related `webpack.config` should be used by default (with some sane defaults as a fallback, probably?)

**Comment by sapegin** [comment]
@okonet What do you mean by “project-related webpack.config”? How can we find it?

**Comment by okonet** [comment]
Usually it's in a root of the project. But this should be a configurable property, like it is now in `styleguide.config`

**Comment by sapegin** [comment]
@okonet The problem is: it can be anywhere and it can be anything. So it’s the wrong way to assume particular project structure. It’s better to have an easy way to import and extend project’s Webpack config.

Maybe we can do something like that (this can be the default implementation):

```js
loadWebpackConfig: function(env) {
  return require('webpack.config' + env);
}
```

Then we’ll extend this config using [webpack-merge](https://github.com/survivejs/webpack-merge) (see Smart Merging of Loaders section) with Styleguidist specific setup.

**Comment by okonet** [comment]
I even think that this is too complex. IMO just a path or a resolved path would suffice.

I don't think that it's just loaders section. webpack allows you to pass configurations to loader using arbitary objects in the config. See postcss-loader for instance: https://github.com/postcss/postcss-loader#usage. So this should be also copied to the final webpack config.

**Comment by okonet** [comment]
One thought I recently had is to convert styleguidist configuration to a webpack plugin which will then added to a user's webpack config. Do you think this could solve some of the issues?

**Comment by sapegin** [comment]
> IMO just a path or a resolved path would suffice

Maybe. But it should be a function anyway like:

```js
resolveWebpackConfig: function(env) {
  return './webpack.config' + env);
}
```

>  I don't think that it's just loaders section.

It’s not *just loaders section*, webpack-merge merges everything. Merging of other sections just doesn’t require magic.

> One thought I recently had is to convert styleguidist configuration to a webpack plugin which will then added to a user's webpack config.

Not sure I understand 8-) Can you show it?

**Comment by okonet** [comment]
> It’s not just loaders section

Okay then. From your first response I understood it like you would just merge loaders section into your webpack config.

> Not sure I understand 8-) Can you show it?

Not sure either. Was just a thought if using webpack plugin architecure could help simplify configuration of the styleguidist.

**Comment by torvalde** [comment]
For me it would be best not to use the existing webpack config of the project, I already have some differences between my prod config, dev config and karma config so I need to separate them, one more place to update would not matter too much for me. These files do not change so much anyway, and it is more important for me to have some flexibility in configuring the styleguide pipeline/avoid situations where I can't upgrade something because of some incompatibility.

The best for me would be to have an optional webpack section in the styleguide.config.js file, similar to the webpack section in karma.conf.js when using karma-webpack.

**Comment by sapegin** [comment]
@torvalde You’ll be able to use `updateWebpackConfig` but there will be no default loaders for project’s code.

**Comment by mik01aj** [comment]
Imho the current approach with implementing some custom `updateWebpackConfig` function in config is OK. It isn't very friendly, but it is flexible. We could try to do some smart config detection, or just recommend doing something like:

```
// styleguide.config.js
updateWebpackConfig: function(webpackConfig) {
  var merge = require('webpack-merge');
  return merge(require('./webpack.config.js', webpackConfig));
}
```

If you want to discuss this further please let's open a new issue for this; this one is just for collecting stuff we'd like to have in 2.0.

**Comment by sapegin** [comment]
Not sure about `peerDependencies` because it’s not just Webpack and Babel but:

```
    "babel-core": "6.5.1",
    "babel-loader": "6.2.2",
    "babel-preset-es2015": "6.5.0",
    "babel-preset-react": "6.5.0",
    "babel-preset-react-hmre": "1.1.0",
    "babel-preset-stage-0": "6.5.0",
    "babel-runtime": "6.5.0",
    "babel-standalone": "6.4.4",
    "webpack": "1.12.13",
```

Should we move everything?

**Comment by mik01aj** [comment]
It's a hard question :)

If we really need these exact version numbers, it's good not to force the users to use the same version for their projects via `peerDependencies`. If we use `dependencies` it's possible to use different versions.

On the other hand, if users really use different version than of webpack than styleguidist, then the configs are incompatible and they have bigger problems. The same with Babel.

**Comment by sapegin** [comment]
Anyway it’s not possible (as far as I know) to work with different major versions of Babel or Webpack so `peerDependencies` looks like over-complication.

**Comment by mik01aj** [comment]
Maybe we could have them all in `dependencies`, just like now, and *detect* version of webpack and Babel that is used in the parent project so that when they are different we could display a warning like "You use Babel 5 in your project, but Styleguidist uses Babel 6, hence your configuration in .babelrc can't be used to build the styleguide.". (Note that if the versions are compatible and npm@3 is used, it will install just one version :+1:)

**Comment by sapegin** [comment]
Yep, that’s the best solution I think.

**Comment by sapegin** [comment]
[2.0.0-rc4](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0-rc4) includes most of the planned changes. Please test it and leave feedback.

**Comment by sapegin** [comment]
[2.0.0-rc6](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0-rc6) is out. I do not plan any changes except possible bug fixes and going to release 2.0.0 on Monday.

**Comment by sapegin** [comment]
[2.0.0](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0) is out.

:shipit: :shipit: :shipit:

**Comment by mik01aj** [comment]
@sapegin, :+1: :tada: 

> Babel 6 is required now.

Could you elaborate on this? That's not very clear, because this can mean either:

* Styleguidist uses Babel 6. (and the dependency will be installed automatically, so why should I care?)
* If I want to use Styleguidist, my project must use Babel 6. (What if I don't use babel at all? What if I have Babel 6?)

Also, I think that we should also explain that the examples always use JSX+ES6+HMR (unlike component code) and that's not even configurable (AFAIK).

**Comment by sapegin** [comment]
> Styleguidist uses Babel 6

Yes.

> the dependency will be installed automatically

Yes.

> If I want to use Styleguidist, my project must use Babel 6

Yes.

> What if I don't use babel at all?

No problem, but you should configure proper Webpack loaders for your project.

> What if I have Babel 5?

Upgrade to Babel 6 or use Styleguidst 1.x.

If you can improve the docs, please do it ;-)

**Comment by mik01aj** [comment]
See #89.
