### ISSUE TITLE
Babel 5 and 6 incompatibility issue (plugin ... didn't export a Plugin instance)

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#65]
Styleguidist currently uses Babel 5, and my project uses Babel 6.

I have babel config in my `package.json`, containing the following:
```
  "babel": {
    "plugins": ["transform-react-jsx"],
    "ignore": ["node_modules/**/*"]
  },
```

Then when I start `styleguidist server`, I get: 

    Module build failed: TypeError: The plugin "transform-react-jsx" didn't export a Plugin instance

This happens because Styleguidist webpack config uses Babel 5, it loads plugins as specified in `make-webpack-config` (which is fine, these plugins are all compatible), **and the plugins from babel config in the upper directory** (which is a Babel 6 plugin, thus incompatible with Babel 5).

**Comment by mik01aj** [comment]
I found a workaround for now - it seems to work when I add `../` to stuff in my `styleguide.config.js`, and run the server like this:

    (cd node_modules; ./react-styleguidist/bin/styleguidist server --config ../styleguide.config.js)

Normally I would just run it with:

    ./node_modules/react-styleguidist/bin/styleguidist server --config styleguide.config.js

We depend way too much on `process.cwd()`...

**Comment by mik01aj** [comment]
Another workaround is to move the babel config from `package.json` or `.babelrc` to other files where it's needed (like test runner, webpack config, ...). **But it's still a workaround, not a fix.**

**Comment by sapegin** [comment]
Will moving Babel to peerDependencies helps here?

**Comment by mik01aj** [comment]
Not sure. If you move it to peerDependencies, it's like saying "this version of styleguidist works only with babel 5" (or only 6). (or, we would have to move all the needed babel plugins to peerdependencies too). But... AFAIK even when the peer dependency can not be met, npm will still install the package. It's complicated...

I think there's a bigger decision to make: do we want styleguidist to **integrate tightly with existing user's libraries** (like babel, webpack) or to have a **standalone that has its own dependent libraries** (so in theory, it works no-matter-what)?

**Comment by sapegin** [comment]
Isolation is definitely better as much as possible. I’m not sure we can use totally independent version of Babel but it would be the best option.

**Comment by sapegin** [comment]
[2.0.0-rc](https://github.com/sapegin/react-styleguidist/releases/tag/2.0.0-rc) uses Babel 6. I’m closing this for now, feel free to reopen if you still have issues or have ideas how to make it better.
