### ISSUE TITLE
We need to change our flexbox layout to something else (poor rendering performance)

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#68]
The single reason is: performance.

![image](https://cloud.githubusercontent.com/assets/3027415/12033557/a292869e-ae24-11e5-9f97-e746cec59805.png)

In this recorded timeline I'm playing with a simple progress bar component. And it seems that anything that *might* become bigger than page width would cause a full page layout recalculation and re-render (I mean browser rerender, not react). (Rendering is purple in these graphs)

Attaching the nav always via `position: fixed` and having a `margin-right` on `Layout` should fix this.

**Comment by sapegin** [comment]
Could you try it please?

**Comment by mik01aj** [comment]
![image](https://cloud.githubusercontent.com/assets/3027415/12034011/1d32beae-ae2b-11e5-9199-4d9e7770604f.png)

Disabling this single rule makes animations smooth as silk.

**Comment by mik01aj** [comment]
Closed in #92.
