### ISSUE TITLE
Add ability to change bundle directory prefix

### ISSUE THREAD

**Issue by stinoga** [sapegin/react-styleguidist#70]
Some users need to call the bundle file using an environment prefix, or path to a CDN. Would like to see a config option to add this prefix to the bundle path.

If this is something you'd like to see in the main repo, I can submit a pull request.

**Comment by sapegin** [comment]
You can change it via `updateWebpackConfig` or I miss something? Not sure that such options in the config will be good because there are so many thing that can be changed in the Webpack config ;-)
