### ISSUE TITLE
Chars like < and & are displayed as &lt; and &amp;

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#71]
I have this in my `examples.md`:

```
default. Note that the size should be a number and not a string. `<Avatar size="42" />` will not work.
```

And this is rendered as:

![image](https://cloud.githubusercontent.com/assets/3027415/12292498/bc5797b6-b9ed-11e5-86cf-1349a9ef589d.png)

**Comment by sapegin** [comment]
Probably it was introduced after moving to MarkdownIt.

**Comment by mik01aj** [comment]
For reference - `markdown-react-js` handles this correctly:

![image](https://cloud.githubusercontent.com/assets/3027415/12294371/279833da-b9fa-11e5-9e91-6b0070d75f08.png)

**Comment by sapegin** [comment]
Then it’s somewhere in the examples loader.

**Comment by mik01aj** [comment]
Related: `<!-- --->` comments that I used for [separating consecutive code blocks](http://meta.stackexchange.com/a/152359/147841) are now displayed as plain text (and they shouldn't).

**Comment by mik01aj** [comment]
@sapegin, is there any chance for having this fixed in 2.0?

**Comment by sapegin** [comment]
There is a chance but pull request will make it 100% ;-)

**Comment by sapegin** [comment]
Even if I enable html in MarkdownIt and rules for that it’s displayed as regular text probably [because of this](https://github.com/alexkuz/markdown-react-js/blob/8693337bf00a71f9fcd35aa6e2cfee99ffeb0a09/src/index.js#L56-L62).

**Comment by mik01aj** [comment]
Okay, but I understand that the bug with `&lt;Avatar size=&quot;42&quot; /&gt;` is fixed anyway, right?

**Comment by sapegin** [comment]
Yep! So I’d like to close it for now and suggest using fenced blocks to separate code blocks.

**Comment by mik01aj** [comment]
Great, thanks! :+1:
