### ISSUE TITLE
Format shape[] just as nicely as shape in the propTypes table.

### ISSUE THREAD

**Issue by mik01aj** [sapegin/react-styleguidist#73]
Current behaviour for `PropTypes.shape({...})`:

![image](https://cloud.githubusercontent.com/assets/3027415/12421281/bf5770e8-bec1-11e5-95c7-ab05f8dca175.png)

Current behaviour for `PropTypes.arrayOf(PropTypes.shape({...}))`:

![image](https://cloud.githubusercontent.com/assets/3027415/12421302/e0884c4c-bec1-11e5-8126-1f1ba87ea4be.png)

**Comment by tizmagik** [comment]
What's the desired behavior?

**Comment by mik01aj** [comment]
To show the shape details in "description" (as on the first screenshot).

**Comment by sapegin** [comment]
![image 2016-07-18 at 2 37 48 pm](https://cloud.githubusercontent.com/assets/70067/16914923/3973a5a6-4cf5-11e6-8d96-d1c0cec5a778.png)

**Comment by mik01aj** [comment]
🎉  😀

**Comment by n1313** [comment]
I have a prop that is an array of shapes, which have a `oneOf` enum prop:

    prop: React.PropTypes.arrayOf(
        React.PropTypes.shape({
            innerProp: React.PropTypes.oneOf(['one', 'two'])
        })
    ),

Is there a nice way to display the values of `innerProp`? Currently I have to resort to typing them out manually in the prop comment.

**Comment by sapegin** [comment]
@n1313 It should be supported according to the source: https://github.com/styleguidist/react-styleguidist/blob/master/src/rsg-components/Props/PropsRenderer.js#L81-L85

If not it’s a bug most probably.

**Comment by mancioshell** [comment]
Is it possible to have similar behaviour for exact proptype ?
