### ISSUE TITLE
Styleguide failing after build.

### ISSUE THREAD

**Issue by jamieholliday** [sapegin/react-styleguidist#74]
Styleguide is working fine on dev server but fails after build with this error:

>Uncaught Error: Cannot detect component name for .../src/components/Column/Column.js

I have done a little poking around and the array of components that are the argument to setComponentsNames() in src/utils/utils.js look like this when running build (in Chrome Devtools):

```
{
examples: Array[1]
filepath: " .../src/components/Column/Column.js"
module: function (props)
pathLine: "components/Column/Column.js"
props: Object
}
```

but are like this when running the dev server:

```
{
examples: Array[1]
filepath: ".../src/components/Column/Column.js"
module: function Column(props)
name: "Column"
pathLine: "components/Column/Column.js"
props: Object
}
```

So as far as I can tell the function that is module and the name property are a bit different and thats whats causing the error. Not sure how to fix this though

**Comment by sapegin** [comment]
Can you share some code that I can debug?

**Comment by mik01aj** [comment]
Maybe it's because you have `.../` instead of `../`.

**Comment by jamieholliday** [comment]
I added the .../ so as not to write out the full path to the files in the example above. Sorry if its a bit confusing. The filepath is actually the correct full path to the file.
@sapegin - I've made a test case in this repo:
https://github.com/jamieholliday/react-styleguidist-testcase
It only includes one component called <Test />
This will demonstrate the error. I was thinking maybe was something to do with webpack. I did have to add a workaround in package.json script to get it to work in the first place with my current setup:
"styleguide": "BABEL_ENV=styleguidist styleguidist server",

**Comment by jonathanp** [comment]
I just ran into the same error, haven't had time to debug it yet though.

**Comment by mik01aj** [comment]
You can try specifying the `displayName` explicitly. (See also https://github.com/sapegin/react-styleguidist/issues/63)

**Comment by jamieholliday** [comment]
Explicitly adding displayName appears to fix the issue

**Comment by sapegin** [comment]
Please try 2.0.0-rc3.
