### ISSUE TITLE
Wrap in wrapper

### ISSUE THREAD

**Issue by jardakotesovec** [sapegin/react-styleguidist#75]
We are using [react-intl](https://github.com/yahoo/react-intl) in many components. These components access intl features via context. 

I could wrap it in every example, but thats not nice solution. So would be nice to have that as option. My quick hardcoded fix looks like:
```
export default class Wrapper extends Component {
	static propTypes = {
		children: PropTypes.node.isRequired
	}

	render() {
		return (
			<IntlProvider locale='en' initialNow={ Date.now() }>
				{this.props.children}
			</IntlProvider>
		)
	}
}
```

So what I basically needs is to have option in `styleguide-config.js` that would be function that can do the wrapping.

So Wrapper component would like something like this:
```
export default class Wrapper extends Component {
	static propTypes = {
		children: PropTypes.node.isRequired
	}

	render() {
                const wrapperFn = this.props.config.wrapperFn;
                return wrapperFn ? wrapperFn(this.props.children) : this.props.children
	}
}
```

I can provide PR if you want, in that case just not sure what make sense more to you - if pass the whole `config` down..  or just that specific option through component hierarchy. In other words how to get to `wrapperFn` option down to `Wrapper` component. 

Thanks for feedback!

**Comment by sapegin** [comment]
I don’t understand how it’s differ from [the Wrapper component](https://github.com/sapegin/react-styleguidist#how-to-change-the-behaviour-of-a-style-guide).

**Comment by jardakotesovec** [comment]
@sapegin I apologize.. I just went through the config options and missed that wrapper component can be replaced like this - which is exactly I need.  

Thanks!
