### ISSUE TITLE
Missing propTypes for getDefaultProps results in tricky exception

### ISSUE THREAD

**Issue by jardakotesovec** [sapegin/react-styleguidist#77]
I was getting
```
TypeError: Cannot read property 'name' of undefined
Props.renderType
/.../node_modules/react-styleguidist/src/rsg-components/Props/Props.js

```

And could not figure out why. Apparently reason was that one of values that was returned from `getDefaultProps` was not defined in `propTypes` in one of my components.

Maybe just some warning instead of 'unknown' exception. Alternatively exception with better explanation would also be good.

Very cool tool btw :+1:  .

**Comment by mik01aj** [comment]
I just experienced the same problem and I can tell it's damn hard to debug this. The error looks like this:

![screenshot 2016-01-27 14 59 25](https://cloud.githubusercontent.com/assets/3027415/12615557/aa8e1662-c506-11e5-8245-631f5c80a68c.png)

Most importantly, there's no information about which component caused the error. (That stacktrace is pretty useless, btw. Maybe we should get rid of `redbox-react`.)

**Comment by sapegin** [comment]
redbox is cool ;-) But probably we can do something with this error.

**Comment by mik01aj** [comment]
@sapegin when you have a big red screen and no idea what caused this, it's not cool. It's much better to show the error in context, so that it's clear what caused the error. Like this:

![image](https://cloud.githubusercontent.com/assets/3027415/12650383/e80faf32-c5e2-11e5-9085-54a7bbc4c2c3.png)

**Comment by sapegin** [comment]
@mik01aj It’d be cool if you can do it ;-)

**Comment by mik01aj** [comment]
@sapegin how about using https://github.com/travelio/fineway-react-error instead of redbox?

**Comment by sapegin** [comment]
I can’t answer until they add readme and license.

**Comment by karlbright** [comment]
Thanks for opening this issue @jardakotesovec. I too ran into this issue and wasn't able to work it out across the large application codebase. I'm interested to see how this progresses.

**Comment by sapegin** [comment]
If someone could submit a fix I’ll be very happy ;-)
