### ISSUE TITLE
Consider using lodash-es modules

### ISSUE THREAD

**Issue by oliverturner** [sapegin/react-styleguidist#83]
Any interest in migrating to lodash-es? Could be nice from a Webpack2 / tree-shaking perspective (dependent on statically analysable imports)

Example here: https://github.com/reactjs/redux/pull/1372/files

**Comment by mik01aj** [comment]
As far as I understand, this would help reduce the bundle size a bit. Is there any other impact that I'm missing?

**Comment by oliverturner** [comment]
Better support in IDEs that perform inline static analysis (Atom + Tern.js, IDEA-based, etc.) is another up-side. Not aware of any negative impacts.

**Comment by sapegin** [comment]
Good idea. But I don’t like this Lodash plugin, I think just importing modules as `lodash-es/func` is enough.

**Comment by sapegin** [comment]
@oliverturner Do you want to make a PR for that?

**Comment by oliverturner** [comment]
Happ to :)

**Comment by sapegin** [comment]
@oliverturner Ping ;-) Do we still want it?

**Comment by sapegin** [comment]
@oliverturner Feel free to reopen or send a pull request ;-|

**Comment by oliverturner** [comment]
Hey @sapegin really sorry for the delay... been swamped for ages :(

Closing for now: will reopen as soon as time permits
