### ISSUE TITLE
Project's .babelrc overrides styleguidist Babel settings

### ISSUE THREAD

**Issue by pekala** [sapegin/react-styleguidist#85]
I had a following `.babelrc` file in my project: 
```
{
    "presets": [
        "react",
        "es2015"
    ],
    "plugins": [
        "transform-object-rest-spread",
        "transform-react-display-name",
    ],
    "env": {
        "development": {
            "presets": ["react-hmre"]
        },
    }
}
```
I couldn't generate or serve the styleguide, as I was getting errors like
```
Module build failed: SyntaxError: ......./node_modules/react-styleguidist/src/components/StyleGuide/StyleGuide.js: Unexpected token (7:18)
   5 |
   6 | export default class StyleGuide extends Component {
>  7 |  static propTypes = {
     |                   ^
   8 |      title: PropTypes.string.isRequired,
   9 |      components: PropTypes.array.isRequired
  10 |  }
```
It turns out that it was because I didn't use `stage-0` preset in my `.babelrc`. It seems that styleguidist should specify that it needs this preset in its own configuration, or the docs should be updated to reflect this requirement.

**Comment by sapegin** [comment]
Yeah, I’m going to disable reading user’s `.babelrc` files as [suggested here](https://github.com/sapegin/react-styleguidist/commit/522b825029d9dbad1216c65ccfb91ca97d8cb790#commitcomment-16029891).
