### ISSUE TITLE
updateExample setting to include encoding (value.substring is not a function)

### ISSUE THREAD

**Issue by giocodes** [sapegin/react-styleguidist#952]
While using the [documentation example](https://react-styleguidist.js.org/docs/configuration#updateexample) for the `updateExample` setting I was getting the following error on the UI: `value.substring is not a function` 

While debugging I realized that `fs.readFileSync(filepath)` was returning the Buffer instead of a string. 

I was able to fix it by simply passing an encoding setting:

`content: fs.readFileSync(filepath, 'utf8'),`

I'm wondering if this is a problem only on certain versions of node... I would be happy to make a PR to update the documentation if you think having the encoding setting is the best way to display this example. 

This feature is so valuable that it would be great to have it in the cookbook under something like "how to display the source code of a file?". Also happy to help with that if you like it.

**Comment by sapegin** [comment]
> I'm wondering if this is a problem only on certain versions of node... 

I think the example wasn't really tested, so your'e change should be fine. And a PR for that would be super awesome!

> This feature is so valuable that it would be great to have it in the cookbook under something like "how to display the source code of a file?". Also happy to help with that if you like it.

That would be super cool too! Thank you!
