### ISSUE TITLE
styleguidist command not found

### ISSUE THREAD

**Issue by ahmed1490** [sapegin/react-styleguidist#97]
<img width="708" alt="screenshot" src="https://cloud.githubusercontent.com/assets/623510/13498759/916526b4-e15b-11e5-9f8d-211a873d6658.png">

**Comment by mik01aj** [comment]
You didn't read the README: 

> 
> ## CLI commands and options
> 
> These commands supposed to be placed in `package.json` `scripts` (see Installation section above). If you want to run them directly, use `./node_modules/.bin/styleguidist`.
> 
> `styleguidist server`: Run dev server.
> 
> `styleguidist build`: Generate a static HTML style guide.

**Comment by sapegin** [comment]
Reading is hard 8-)

**Comment by ahmed1490** [comment]
somehow i missed ` If you want to run them directly, use ./node_modules/.bin/styleguidist`
my bad!
