### ISSUE TITLE
Add routing to Styleguidist

### ISSUE THREAD

**Issue by zammer** [sapegin/react-styleguidist#98]
For the project I'm working on we implemented simple routing (not including react-router because we didn't need the more advanced functionality). 

We have a homescreen then each component has it's own page.
Is this something you may interested in?
If so would you want to use react-router?
Also should there be an option to have a one page or multi page app? (Not thought how to implement this)

**Comment by sapegin** [comment]
Not sure about one page per component but routing is definitely a good thing to have because we want to add components grouping (by tag or function or whatever) and ability to add random Markdown and HTML documents to style guide.

Also check this issues: #31, #12.

**Comment by sapegin** [comment]
There is very basic routing implementation and ability to open a component in a separate page now. Feel free to open a separate issue or submit a pull request if you want something more specific.

**Comment by mik01aj** [comment]
@sapegin we have filtering (#123), but can we actually have an URL that would jump straight to the single component view? Maybe I'm missing something.

**Comment by sapegin** [comment]
@mik01aj I’ve added links yesterday but the UI is not the best. But better than nothing because I always forget this `#!/Button`.

**Comment by sapegin** [comment]
![](http://wow.sapegin.me/1e3t2b3U0u2v/Screen%20Recording%202016-06-24%20at%2010.19%20AM.gif)

**Comment by eduardoinnorway** [comment]
What is the status here? I would like to have one page per group of components ...

**Comment by pnepe6** [comment]
We would like to have a site next to our documentation, I've been trying to implement react-router-redux but I can't get wih this configuration another path served than `/`. Every created route return 404. any idea
